### ISSUE TITLE
[Dotty/Lneato/Lefty] dot(ty) fails on long labels     

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#1068]
Ported Issue from Mantis
Original ID: 419
Reported By: Nico Kasprzyk

SEVERITY: CRITICAL
Submitted: 2004-06-22 17:07:25

OS: *-LINUX-2.6.7

VERSION: 1.1.2

DESCRIPTION
-----------

<br>

In our project, we automatically create dot-Files with sometimes long
labels for nodes. The parser break the processing with:
<br>

graph parser: string ran past end of line near line 249
<br>

I also send you the dot-File and hope that this problem is not a big one
to solve.
<br>

Kindly regards,
<br>

Nico

ADDITIONAL INFORMATION
----------------------

[erg] This is not a bug. There are newline characters within quoted
strings. One can either make the string into a single line, or use
backslash before a newline, or the "+" string operator.

It turns out the original input file had introduced newline characters,
and user reported the problem in dot. It appears the problem is in dotty,
not dot. The new input file has a long line, which dotty rejects.

**Comment by GadgetSteve** [comment]
Marked as fixed in git log so closing.

**Comment by richie50** [comment]
"One can either make the string into a single line or use the backslash before a newline, or the "+" string operator". I did this but I still get the same error because my string is very long

**Comment by emden** [comment]
Can you post your input graph and how you are running it? Also, what version of Graphviz are you using? (run dot -V) Thanks.
