### ISSUE TITLE
testing issue using file attachments

### ISSUE THREAD

**Issue by magneticnorth** [ellson/graphviz#1144]
[Infovis Best Papers.txt](https://github.com/ellson/graphviz/files/376928/Infovis.Best.Papers.txt)
[t.txt](https://github.com/ellson/graphviz/files/376939/t.txt)

[edge.txt](https://github.com/ellson/graphviz/files/376943/edge.txt)
[edge.txt](https://github.com/ellson/graphviz/files/376944/edge.txt)

**Comment by ellson** [comment]
[Uploading edge.txt…]()

**Comment by ellson** [comment]
don't think that worked ...

**Comment by ellson** [comment]
[edge.txt](https://github.com/ellson/graphviz/files/376949/edge.txt)

**Comment by ellson** [comment]
The issue here is that "github issues" doesn't accept ".gv" files as attachments. 

Not really a graphviz issue,  so closing.
