### ISSUE TITLE
Setting DYDL_LIBRARY_PATH to intel-mkl breaks graphviz

### ISSUE THREAD

**Issue by kirk86** [ellson/graphviz#1160]
Hi I would like to point out the following error regarding graphviz. Every time that I set the DYLD_LIBRARY_PATH to intel-mkl libraries makes graphviz unusable. Resulting in errors saying that cannot find the necessary libraries such as pango.dylib and others which in fact are present in the system.

Once I comment that out graphviz works fine. How can I resolve this issue since I want to be able to set DYLD_LIBRARY_PATH to intel-mkl libraries and at the same time use graphviz.

My system is OS X 10.11.

**Comment by emden** [comment]
DYLD_LIBRARY_PATH can be a colon-separated list, so you should be able to have it contain the path to the intel-mkl libraries as well as the path the graphviz libraries.

**Comment by kirk86** [comment]
This is what I have:

```
export MKLROOT=/opt/intel/mkl
export DYLD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2016.3.170/mac/compiler/lib:/opt/intel/mkl/lib:/usr/local/opt/openblas/lib:${DYLD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=/usr/local/Cellar/open-mpi/2.0.0/lib:/usr/local/Cellar/libiomp/20150701/lib:${DYLD_LIBRARY_PATH}
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2016.3.170/mac/compiler/lib:/opt/intel/mkl/lib:/usr/local/opt/openblas/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/opt:/usr/local/opt/openblas/lib:${LD_LIBRARY_PATH}
export NLSPATH=/opt/intel/compilers_and_libraries_201.63.170/mac/mkl/lib/locale/%l_%t/%N:${NLSPATH}
export MANPATH=/opt/intel/compilers_and_libraries_201.63.170/mac/man/common:/usr/local/share/man:/usr/share/man:/opt/intel/man:${MANPATH}
export INCLUDE=/opt/intel/compilers_and_libraries_2016.3.170/mac/compiler/include:/opt/intel/mkl/include:/usr/local/opt/openblas/incldue:${INCLUDE}
export CPATH=/opt/intel/compilers_and_libraries_2016.3.170/mac/compiler/include:/usr/local/opt/openblas/include:${CPATH}
bash /opt/intel/compilers_and_libraries_2016.3.170/mac/bin/compilervars.sh -arch intel64 -platform mac
```
I've checked all of them one by one and `DYLD_LIBRARY_PATH` is the one that causes the error.
I think that maybe its getting confused with default apples accelerate framework. I don't know how to resolve this.

**Comment by magneticnorth** [comment]
What's the value of DYLD_LIBRARY_PATH after executing the above? I don't set DYLD_LIBRARY_PATH (and I'm on OSX 11.6 too).  Exactly what's the error? Don't you need /usr/local/lib and maybe /usr/local/lib/graphviz in the dynamic library path?

**Comment by emden** [comment]
I believe what is happening is that when the dot tools are linked, the binaries maintain the directories where the dynamic libraries are stored. When you set DYLD_LIBRARY_PATH, this overrides that built in information, so you need to add the necessary paths to DYLD_LIBRARY_PATH.

**Comment by magneticnorth** [comment]
Yes, and you can determine the necessary paths by running otool -L on the dot executable
and the plugins to see where they are finding other libraries.

What program are you trying to speed up by using Intel MKL?

**Comment by kirk86** [comment]
some libraries such theano and torch... So if I understand correctly you're saying that I should also add graphviz libraries to DYLD_LIBRARY_PATH? 

Should those come first regarding the path order?

For instance:

`DYLD_LIBRARY_PATH=/path/to/graphviz/lib:/path/to/mk/intel` 

or it doesn't matter?

**Comment by kirk86** [comment]
Hi everyone, so I just added `/usr/local/lib and /usr/local/lib/graphviz` to `DYLD_LIBRARY_PATH` as @magneticnorth suggested. I then tested a minimal example which I know it works if I don't set up the `DYLD_LIBRARY_PATH` and I get the following errors. Any suggestions on how to resolve this issue...?

```
Warning: Could not load "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/libgvplugin_pango.6.dylib" - file not found
Warning: Could not load "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/libgvplugin_pango.6.dylib" - file not found
Warning: Could not load "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/libgvplugin_quartz.6.dylib" - file not found
Warning: Could not load "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/libgvplugin_pango.6.dylib" - file not found
Warning: Could not load "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/libgvplugin_pango.6.dylib" - file not found
Warning: Could not load "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/libgvplugin_gd.6.dylib" - file not found
Format: "png" not recognized. Use one of: bmp canon cgimage cmap cmapx cmapx_np dot eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4
```

**Comment by emden** [comment]
How are you installing Graphviz? Using home brew or by hand? It certainly appears that some piece is picking up a different, home brew library, which then looks for libraries installed by home brew.If you are not building  using home brew, you will need to uninstall the library that is getting in the way. If you are using home brew, then why aren't those libraries there under Cellar? You might also want to ping the person maintaining Graphviz on home brew.

**Comment by kirk86** [comment]
@emden thanks for the response. I just install it using home brew. If I check the libraries they exist under that particular path. Those errors come from when I run a simple minimal example through python or when I execute `dot -Tpng`.

I agree that something is interfering but I cannot find out what exactly it is!

**Comment by magneticnorth** [comment]
I don't think we can debug this unless you want to give us ssh access to your computer.

**Comment by emden** [comment]
Very odd that somebody reports that the files are missing but they are there. You definitely might want to add someone from home brew to the discussion.

**Comment by kirk86** [comment]
@emden Thanks for the suggestions. I think that I've temporarily managed to fix that with the help/suggestion of @magneticnorth above. I'm closing this issue for now in the hope that things will work out. In case of any hiccups  I'll report back.

Thanks!
