### ISSUE TITLE
dot : label and xlabel with href generate broken SVG

### ISSUE THREAD

**Issue by jvkucera** [ellson/graphviz#1166]
Following simple example generates broken svg output (dot -Tsvg test.dot > test.svg).

`digraph Test {`

`aaa[shape="box",href="http://www.google.com",label="google",`
`xlabel=<<TABLE><TR><TD HREF="http://www.yahoo.com">yahoo</TD></TR></TABLE>>];`
`}`

Problem in output SVG file is mismatched `<a>` and `</a>` tag.

OS: Linux Fedora release 24
dot: graphviz version 2.38.0 (20140413.2041)

**Comment by emden** [comment]
Fixed.

**Comment by emden** [comment]
The fix provided earlier wasn't correct, in that it broke other graphs, and also didn't fix the possibility of duplicate ids. This should all be fixed now with e3b4f50920900a7f532e7108d7f920ac77f2f5b4.
