### ISSUE TITLE
Build docs out of sync, dead link

### ISSUE THREAD

**Issue by eelstork** [ellson/graphviz#1170]
http://ellson.github.io/graphviz/doc/html/build.html and doc/build.html do not refer the same link for Windows build notes.
The github.io documentation (clickable so, possibly the natural choice) refers 
http://www.graphviz.org/pub/scm/graphviz2/doc/winbuild.html
which may return a forbidden error.

http://www.graphviz.org/doc/winbuild.html is linked from doc/build.html. It would be nice to have this on github where it might get patches and updates.

Is there a reason to refer build notes on github.io?

**Comment by ellson** [comment]
Should be fixed.  I changed the URL to a relative link.


Thanks for the report


John

**Comment by ellson** [comment]
Change in source tree hasn't propogated to https://ellson.github.io/graphviz/doc/html/build.html yet.    Not sure how that happens.  Stephen?

**Comment by Chiel92** [comment]
Still not working

**Comment by ellson** [comment]
Please try now.  Thank you for your patience.

**Comment by Chiel92** [comment]
It works now!

**Comment by Chiel92** [comment]
This issue can be closed.
