### ISSUE TITLE
Trying to compile on windows: cannot open include file: 'libltdl/lt_system.h'

### ISSUE THREAD

**Issue by Chiel92** [ellson/graphviz#1186]
I'm trying to build graphviz on windows using Visual Studio 2015, but I'm currently stuck with this error. I've got the cgraph project to build, now gvc is next. What I did so far:

1. Install libtool from gnu win 32
2. Install sed from gnu win 32
3. Install pcre from gnu win 32
4. Install zlib from gnu win 32
5. Add the gnu paths to the project parameters
6. Undefine HAVE_EXPAT* in windows/include/config.h

This is the error message:

```
  c:\users\chiel.tenbrinke\projects\graphviz\lib\common\utils.c(22): fatal error C1083: Cannot open include file: 'libltdl/lt_system.h': No such file or directory [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
```

Any idea where to get this header file? As noted above, I did install libtool, but it didn't come with any `lt_system.h` header file.

Full compiler output: https://justpaste.it/11e72

**Comment by ellson** [comment]
I can only tell you how it works on Linux.


That file is generated by "libtoolize" which is run from autoreconf which is run from ./autogen.sh


I've no idea if libtool supports dynamically loaded libraries on Windows?  (i.e. libs that are loaded on demand, but not necessarily at the start of the invocation.)


A work-around would be to use:  ./configure --enable-static


John

**Comment by Chiel92** [comment]
> That file is generated by "libtoolize" which is run from autoreconf which is run from ./autogen.sh

All right, I will try to get that script to run and see what happens.

> I've no idea if libtool supports dynamically loaded libraries on Windows?  (i.e. libs that are loaded on demand, but not necessarily at the start of the invocation.)

I don't know either, but I would expect it to work, as libtool is available for windows.

> A work-around would be to use:  ./configure --enable-static

Would that actually affect the vcxproj files for visual studio?

**Comment by Chiel92** [comment]
> All right, I will try to get that script to run and see what happens.

Too bad:

```
$ bash autogen.sh
Graphviz: version date is based on time of last commit: 20161214.1421
Graphviz: abbreviated hash of last commit: 7db422b
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4te::ChannelDefs module) (@INC contains: C:/PROGRA~2/GnuWin32/autoconf/share/autoconf /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
```

**Comment by Chiel92** [comment]
> A work-around would be to use:  ./configure --enable-static

Btw, I wouldn't expect this to fix the build error, as the #include directive will still be there. 
This include directive is only enclosed by an `#ifdef _WIN32`, which is always true on windows.

**Comment by ErwinJanssen** [comment]
For building on Windows:

- First, in the root of the repository, perform `git submodule update --init`. This will download all submodules, which are mostly the dependencies for Windows.
- Next, add the `windows\dependencies\graphviz-build-utilities` directory to your PATH (and restart Visual Studio or the prompt with which you execute `msbuild` after that). This folder contains the tools Bison, Flex and SED (and future additions) with versions that are tested.
- The final step is building libgd from the source (they do not provide Windows releases), this is a bit of a hassle. The script used in the Appveyor build assumes 7-zip is installed and in the path and that Visual Studio 14.0 is installed.

In Powershell, `cd` to `windows\dependencies\libgd` in the Graphviz repo and run the following lines:

```
wget http://windows.php.net/downloads/php-sdk/deps/vc14/x86/archives/freetype-2.6.2-vc14-x86.zip -O freetype.zip
wget http://windows.php.net/downloads/php-sdk/deps/vc14/x86/libiconv-1.14-vc14-x86.zip -O iconv.zip
wget http://windows.php.net/downloads/php-sdk/deps/vc14/x86/libjpeg-9b-vc14-x86.zip -O jpeg.zip
wget http://windows.php.net/downloads/php-sdk/deps/vc14/x86/libpng-1.6.21-vc14-x86.zip -O png.zip
wget http://windows.php.net/downloads/php-sdk/deps/vc14/x86/zlib-1.2.8-vc14-x86.zip -O zlib.zip
7z x freetype.zip
7z x iconv.zip
7z x jpeg.zip
7z x png.zip
7z x zlib.zip
```

Then, using the `cmd` command prompt, `cd` to the same directory and run the following lines (change the path in the first line if you use a different Visual Studio version):

```
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
set WITH_DEVEL=deps
set WITH_BUILD=build
nmake /f windows/Makefile.vc build_libs
```

If all went right, the dependencies are now set up and you can build Graphviz.

**Comment by ErwinJanssen** [comment]
You can also uncomment the `HAVE_EXPAT` defines, as expat is included as a submodule.

**Comment by Chiel92** [comment]
Thanks for the explanation! Much appreciated.
The project dot builds successfully now!

Would it be a good idea to put that piece of text in README.md?

**Comment by Chiel92** [comment]
Only the debug configuration builds successfully though :)

**Comment by ErwinJanssen** [comment]
Maybe if you perform a `git clean -xfd .` before building to clean the temporary files?

**Comment by Chiel92** [comment]
That helps!

**Comment by Chiel92** [comment]
Any idea why the fonts are not working when rendering with the newly compiled dot dll? It used to work with the installed version of dot.exe.

```
            gvRenderFilename(gvc, ptr, "png", filename);
```


![dump1](https://cloud.githubusercontent.com/assets/1030961/21312160/003d80a8-c5eb-11e6-90fc-3d3ddbae0429.png)

**Comment by ErwinJanssen** [comment]
I can reproduce this error and found the cause. I'll get back to you soon when I have a fix.

**Comment by ErwinJanssen** [comment]
I submitted a fix with a pull request. You can out the change now or wait for it to merge.

**Comment by Chiel92** [comment]
I think this issue can be closed.
