### ISSUE TITLE
Expose cgraph macros as functions in dll api

### ISSUE THREAD

**Issue by Chiel92** [ellson/graphviz#1188]
For some cgraph functionality, macros are provided in stead of functions, I suppose for reasons of performance, as this reduces function call overhead. Examples of this are `aghead` and `ageqedge`.

When programming in C or C++ this doesn't really make a difference, but when using the cgraph dll from a language without a C preprocessor, you can't use macros. Now in the case of `aghead`, there is a function definition given in `graph.c`, which can be used instead of the macro. I.e. you can link against `aghead` and it will just work. *My question is: is this intentional?*

If yes, I would like to do the same for `ageqedge`. If not, I would like to introduce this, albeit in a slightly different way. It'd be more clear if these macro-alternative-functions were declared in `cgraph.h`. You would then be able to choose between either interface by a preprocessor directive.

**Comment by Chiel92** [comment]
Any thoughts?

**Comment by magneticnorth** [comment]
I’m pretty sure the answer is yes, that was done to assist in debugging.

There are plenty of artifacts in the code that reflect its age, an inconsistent obsession
with managing memory usage (but probably not tightly enough), and with compiling
everywhere in the era it was written: BSD, Linux, Solaris, HPUX, AIX, ancient versions
of Visual Studio, IRIX. These days one would assume compilers have inline functions
and one might invest more work favoring gcc or clang -O3 on x86 processors.
