### ISSUE TITLE
dot_static not very static

### ISSUE THREAD

**Issue by ianamason** [ellson/graphviz#1198]
So I built dot_static via:
```
./autogen.sh --prefix=$PREFIX --enable-static --disable-php
```

and on linux I get:

```
 ldd dot_static
	linux-vdso.so.1 =>  (0x00007fffb2fc3000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fb3e4a13000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb3e47e9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb3e45d0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb3e42ca000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb3e3f05000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb3e3d01000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb3e4c1d000)
```

while on Darwin I get:

```
otool -L dot_static
dot_static:
	/usr/local/opt/libtool/lib/libltdl.7.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

```

So either I am misinterpreting the meaning of `static` or I am doing something wrong or else this is an issue ...

**Comment by magneticnorth** [comment]
Yes, it appears something may be wrong here, at least with clang/clang++ on
OSX. I see that dot_static links to dynamic libraries (e.g.
libpango-1.0.0.dylib) although static libraries (e.g. libpango-1.0.a) are
available.   My dot_static links to about 19 different dynamic libraries
and in some cases static library equivalents seem to be available.

That being said, and I know this seems obvious, did you confirm that on
your computer, the static versions of libz, libexpat, libm are available?
I think libltdl is always going to be dynamic (it's a dynamic loader
utility library), the system library is always going to be dynamic, so the
rest of that list is pretty short.

**Comment by magneticnorth** [comment]
I’l just add that if I grep static config.log the result includes
lt_cv_prog_compiler_static_works=no
lt_cv_prog_compiler_static_works_CXX=no

In fact config.log says
configure:10473: checking if gcc static flag -static works
configure:10501: result: no

So much for that.

**Comment by ianamason** [comment]
Good point, let me check.

Darwin:
libexpat    no .a
libz    yes .a, but not in /usr/lib in /usr/local/lib instead

Linux:
libexpat yes, but in /usr/lib/x86_64-linux-gnu/ rather than /lib/x86_64-linux-gnu/l
libz    yes, but in /usr/lib/x86_64-linux-gnu/ rather than /lib/x86_64-linux-gnu/l
libm  ditto

**Comment by ianamason** [comment]
The static stuff in config.log gets the "yes" on linux

**Comment by ianamason** [comment]
Also on linux: /usr/lib/x86_64-linux-gnu/libltdl.a

**Comment by magneticnorth** [comment]
Just to undo the noise I previously added, I realize now that while the
full bore  gcc -static may not work  (it doesn’t on my computer - no libcrt0.o) 
we might still expect the build to pick up static libs where they are available. 
It will take more of an automake expert than me to decide whether we
should also expect them to be preferred if they are in a different 
directory from the dynamic versions, but locally that’s not a problem,
though sometimes the names may not match closely enough, e.g. I have
/usr/local/opt/gd/lib//libgd.3.dylib
/usr/local/opt/gd/lib//libgd.dylib
/usr/local/opt/gd/lib//libgd.a

and my dot_static binds /usr/local/opt/gd/lib/libgd.3.dylib
though possibly all that automake machinery could also notice that
the libgd.dylib sitting next to libgd.a points to libgd3.dylib so maybe all is well.

In general static libs don’t get much respect out there.

**Comment by magneticnorth** [comment]
> On Jan 18, 2017, at 2:43 PM, Ian A Mason <notifications@github.com> wrote:
> 
> The static stuff in config.log gets the "yes" on linux
> 
> 
> 
Then it might be helpful to study config.log and the output of make V=1 and see
why the dynamic libs are preferred?

**Comment by ianamason** [comment]
I put the logs here:

http://csl.sri.com/~iam/dot_static/config.log

and

http://csl.sri.com/~iam/dot_static/make.log

**Comment by ellson** [comment]
The build process doesn't attempt to statically link any system libs.    The word "static" is used only to indicate that there are no additional graphviz-sourced libs or plugins needed by the binary executable.

**Comment by ianamason** [comment]
Not sure I understand the distinction.

Which is, say libgd? 

system or graphviz-sourced?

**Comment by ellson** [comment]
system

the sources for libgd are no longer in graphviz.

The gd-plugin is part of graphviz, so in graphviz-static the wrapper is not loaded dynamically, but the plugin is still linked to the system provided libgd.so

**Comment by ianamason** [comment]
Got it.
