### ISSUE TITLE
Minor anomaly: indentation of agwrite dot output falls short

### ISSUE THREAD

**Issue by Chiel92** [ellson/graphviz#1207]
Example output of `agwrite`:

```
digraph "root graph" {
	graph [label=xx];
	subgraph "cluster_sub graph" {
		graph [label=x];
		"node";
		subnode;
	}
	subgraph "sub graph" {
		graph [label=x];
		"node" -> "node" [key="edge 2"];
	subnode -> subnode [key="edge 3"];
}
"node" -> "node" [key="edge 1"];
subnode -> subnode [key="edge 4"];
}
```

As you see at some point the indentation is shifted back for no apparent reason. It's not really a problem, but it makes the output slightly harder to read. Is this known behavior?

**Comment by emden** [comment]
Fixed in revision 617fd44569ba4b1cabcaded036b19db9028c12b1. This bug goes back at least to the original version of lib agraph. (Not too many people use edge keys.)
