### ISSUE TITLE
[CGraph] How to obtain the edgepair structure given some edge?

### ISSUE THREAD

**Issue by Chiel92** [ellson/graphviz#1212]
In cgraph, an edge is implemented as an edge pair. This means that there are two valid pointers to an edge. I need to write a hash function that maps two edges to identical hash values (integers) when they represent the same edge.

Obviously, using the pointers themselves as hash values won't work, as there are two valid pointers.

My question is, how can this be achieved? Is there maybe a way to obtain the twin sibling of a given edge? If yes, that could be used to construct a hashvalue by e.g. summing the two pointer values.

**Comment by graphviz** [comment]
Yes, there are macros AGMKOUT(e) and AGMKIN(e) that find an in-edge or out-edge
pointer from an edge pointer.  It’s a pretty common situation in the cgraph implementation.
It’s just a little bit of tag checking and arithmetic.

**Comment by Chiel92** [comment]
Allright, they should be exposed as function too then, just like ageqedge. As soon as I have time I will send a PR doing so.
