### ISSUE TITLE
Port to connect an edge to the distinct point in the image

### ISSUE THREAD

**Issue by antanasb** [ellson/graphviz#1216]
Hello, is it possible to specify port coords (in percent or absolute representation) to attach edge's ends to particular pixel of the node's image?
For example, while drawing a computer network, makes sense to connect cable (edge) to the right router's/switch's (image) port.

**Comment by emden** [comment]
At present, Graphviz only supports ports as components of HTML-like label or a record node, or one of eight compass points, or a component and a compass point. Something like what you suggest would not be too hard to implement, though if it allowed an absolute representation, it would probably use points as the unit.

**Comment by antanasb** [comment]
emden, thank you for the clarification. I'll follow GraphViz progress. Cheers!
