### ISSUE TITLE
[Dot] Missing font-opacity in SVG rendering

### ISSUE THREAD

**Issue by v-melot2** [ellson/graphviz#1217]
Hi all,

It seems that the Dot SVG renderer (dot -Tsvg command) ignores font opacity. [That fix](http://www.graphviz.org/bugs/b1869.html) added alpha support for paths and fills, but not for text. I think one should just edit [static void svg_textspan](https://github.com/ellson/graphviz/blob/master/plugin/core/gvrender_core_svg.c#L386) to add the needed attribute.

Thanks.

**Comment by emden** [comment]
Fixed.
