### ISSUE TITLE
Compiling dot dlls for 64 bit on windows

### ISSUE THREAD

**Issue by Chiel92** [ellson/graphviz#1218]
I'm trying to compile the dot dlls on windows 64 bit. Is this supported?

Starting with cdt, I added a x64 project platform, and enabled building cdt in the x64 solution platform.
At the moment I have (sorta) successfully compiled cdt with the following command (in git bash):

```
$ msbuild graphviz.sln //p:platform=x64 //t:cdt
```

and get the following warnings

```
"C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj" (default target) (2) ->
(RunNativeCodeAnalysis target) ->
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dtclose.c(40): warning C6001: Using uninitialized memory 'dt'. [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dthash.c(242): warning C6011: Dereferencing NULL pointer 'r'.  [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dtview.c(65): warning C6011: Dereferencing NULL pointer 'dt'. See line 29 for an earlier location where this can occur [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dtview.c(66): warning C6001: Using uninitialized memory 'o'. [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dtview.c(70): warning C6011: Dereferencing NULL pointer 'd'. See line 29 for an earlier location where this can occur [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dtview.c(75): warning C6011: Dereferencing NULL pointer 'p'. See line 29 for an earlier location where this can occur [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]
  c:\users\chiel.tenbrinke\projects\graphviz\lib\cdt\dtview.c(106): warning C6011: Dereferencing NULL pointer 'dt'. See line 93 for an earlier location where this can occur [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\cdt\cdt.vcxproj]

    7 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.82
```

Does this mean the compilation was successful? The warnings look somewhat threatening, and there are not present in the win32 build.

For cgraph I did a similar thing, but the amount of warnings is too high to post right here.

(If this appears to be all fine, I could commit these configuration additions and give a PR.)

**Comment by ellson** [comment]
I think the warnings are bogus.

- this code has built for 64bit Linux platforms for years.

- The first warning, "lib\cdt\dtclose.c(40): warning C6001: Using uninitialized memory 'dt'. " makes no sense. dt is a function argument, why wouldn't it be reported on the function invocation , also its used in this function before this line?

Maybe try a different compiler? gcc ?

**Comment by Chiel92** [comment]
> Maybe try a different compiler? gcc ?

I'm not sure if that is easily possible. Graphviz provides a Visual Studio .sln file, which I use to compile on windows with the instructions from https://ellson.github.io/graphviz/doc/html/winbuild.html

Afaik, Visual Studio has it's own compiler, which you can't deviate from.

**Comment by Chiel92** [comment]
Compiling gvc doesn't succeed out of the box.

```
"C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj" (default target) (2) ->
(ClCompile target) ->
  c:\users\chiel.tenbrinke\projects\graphviz\lib\common\colortbl.h(2): error C2059: syntax error: '}' [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]

    169 Warning(s)
    1 Error(s)
```

The error is caused by the fact that `colortbl.h` contains only

```
static hsvrgbacolor_t color_lib[] = {
};
```

The build targets that I've added to produce this can be found here

https://github.com/Chiel92/graphviz/tree/64bit_msbuild_targets

**Comment by magneticnorth** [comment]
In the Unix build, in lib/common/Makefile, you can see that an awk script
$(top_srcdir)/awk/colortbl.awk is run to build colortbl.h, as follows:
colortbl.h : color_lib
    $(AWK) -f $(top_srcdir)/awk/colortbl.awk color_lib > colortbl.h
Apparently the script ran but something went wrong as it didn't emit
any definitions from color_lib. Is this being run by the VS build?
Possibly you can copy the file from somewhere else.
See
http://www.graphviz.org/pub/graphviz/development/doxygen/html/colortbl_8h_source.html

On Thu, Mar 23, 2017 at 12:12 PM, Chiel ten Brinke <notifications@github.com

**Comment by Chiel92** [comment]
It appears that `color_lib` is empty, while `lib/common/color_names` does contain text.

**Comment by Chiel92** [comment]
Removing the `/L` switch from the sort command seems to fix it, but I'm not sure what side effects that will have.

Now we end up with unresolved externals.

```
"C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj" (default target) (2) ->
(Link target) ->
  gvc.def : error LNK2001: unresolved external symbol lt_dladderror [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dladdsearchdir [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlcaller_get_data [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlcaller_set_data [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlclose [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlerror [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlexit [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlforeachfile [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlgetinfo [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlgetsearchpath [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlinit [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlinsertsearchdir [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlisresident [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlloader_add [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlloader_find [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlloader_next [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlloader_remove [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlmakeresident [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlopen [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlopenext [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlpreload [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlpreload_default [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlseterror [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlsetsearchpath [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  gvc.def : error LNK2001: unresolved external symbol lt_dlsym [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]
  C:\Users\Chiel.tenBrinke\Projects\graphviz\x64\Debug\gvc.lib : fatal error LNK1120: 25 unresolved externals [C:\Users\Chiel.tenBrinke\Projects\graphviz\lib\gvc.vcxproj]

    181 Warning(s)
    26 Error(s)
```

Those externals indeed seem only to occur in the .def files, git-grepping them doesn't give any other results. Is that supposed to be the case?

**Comment by ErwinJanssen** [comment]
I think we can all agree that the current Windows build is a mess, that is why a CMake build is being created.

All the errors and warnings you encounter are all solved in the current Visual Studio build, adding some new configurations isn't going to work if you don't look at the existing configuration.

I think it is a waste of everybody's time if we add support for 64bit to the current Visual Studio build, or make any large changes to that build at all. We should migrate to a CMake build as soon as possible. I'm working on this, but can't spend much time on it unfortunately. Where I am now: almost all projects from `lib` are included, just like the `core` and `dot_layout` plugins and almost the `dot` executable. A minimal setup with which graphs can be created.

If someone wants to help, I'm happy to collaborate.

I will see how 64bit support can be integrated in the CMake build.

**Comment by Chiel92** [comment]
- I agree that the current build process for windows is messy. Do you blame that on the whole msbuild architecture,  i.e. do you think that switching to a different build system (cmake) will solve things?
- I don't have much time on my hands either, but if you could briefly point out what needs to be done in order to get a 64 bit build of dot.dll and its dependencies, I can make considerations. I really do need that 64 bit build, in the shortest time possible.

**Comment by ErwinJanssen** [comment]
CMake has a few main benefits:
* It is cross platform. So if the Graphviz CMake build is mature enough, replacing Autotools with CMake might be an option and only a single build system will have to be maintained.
* CMake can produce packages for a variety of platforms, this includes a Windows installer.

Creating a 64bit Visual Studio solution with CMake happens to be easy, adding `Win64` to the generator is enough, e.g. `cmake -G "Visual Studio 14 2015 Win64"`. Compiling with this generator causes errors, but I think the cause is in the current DLL import / export structure, I will look into this.

**Comment by Chiel92** [comment]
> Compiling with this generator causes errors, but I think the cause is in the current DLL import / export structure, I will look into this.

That sounds promising. If you make any progress on that, I'm keen to hear about it. Is there anything else that needs to be done to make it all work, maybe porting some remaining projects to CMake?

**Comment by ErwinJanssen** [comment]
It seems the main problem is that the dependencies used on Windows (I store them in [a separate repository](https://github.com/ErwinJanssen/graphviz-windows-dependencies)) are 32bit and can therefore not be linked to 64bit code. But most dependencies are not actively maintained for Windows, so no 64bit binaries are provided... Do you have an idea on how this could be solved?

**Comment by chut89** [comment]
I think most of the dependencies are open source software, so we may grab source code and build 64-bit versions for each of them. Does it sound possible?

**Comment by ErwinJanssen** [comment]
That sounds possible, but also like a lot of work. I know that some dependencies can be found on the [download section of php.net](http://windows.php.net/downloads/php-sdk/deps/), but not all (Pango and Cairo come to mind). Does anyone know of similar trusted sites that distribute these kind of libraries?
Creating an inventory of the required and optional dependencies could also be helpful.

**Comment by twogee** [comment]
Looks like this is what you need

https://tschoonj.github.io/blog/2014/09/29/gtk2-64-bit-windows-runtime-environment-installer-now-on-github/

**Comment by Chiel92** [comment]
Here is a list of dependencies (from https://github.com/ErwinJanssen/graphviz-windows-dependencies) together with the 64 builds that I've been able to found. `GTK-installer` refers to https://tschoonj.github.io/blog/2014/09/29/gtk2-64-bit-windows-runtime-environment-installer-now-on-github/ referred to by @twogee.

```
ANN (version 1.12)                      --
atk (version 1.22)                      -- 2.22 in GTK-installer
Cairo                                   -- 1.15.4 in GTK-installer
The Expat XML Parser (version 2.2.0)    -- (There is a libexpat-1.dll in GTK-installer)
Fontconfig (only .lib and .dll)         -- 2.12.1 in GTK-installer
FreeGLUT (version 3.0.0)                -- 3.0.0 at http://www.transmissionzero.co.uk/software/freeglut-devel/
Freetype (only .lib and .dll)           -- 2.7.1 in GTK-installer
GD Graphics library (version 2.2.0)     -- 
glib (version 2.16.3)                   -- 2.50.3 in GTK-installer
Iconv (only .lib and .dll)              -- libiconv 1.15 in GTK-installer
jpeg (only .lib and .dll)               -- 9b-vc14 at http://windows.php.net/downloads/php-sdk/deps/vc15/x64/
GTK (version 2.12.9)                    -- gtk2.24.31 and 3.22.9 in GTK-installer
LibTool (version 1.5.26)                -- 
Pango and pangocairco                   -- pango 1.40.3 in GTK-installer
PNG                                     -- libpng 1.6.28 in GTK-installer
RxSpencer (version 3.8.g.3)             -- 
zlib (version 1.2.3)                    -- 1.2.11 in GTK-installer
```

If the list is correct, the only remaining unmet dependencies are `ANN`, possibly `expat`, `libgd`, `libtool` and `rxspencer`.

**Comment by twogee** [comment]
Sorry for a naive question, but why there is a need for 2 different XML parsers (expat and libxml)?
libtool helps in building shared libraries, so it is surely not a runtime dependency.
libgd is on GitHub (https://github.com/libgd/libgd);
ANN has an outdated GitHub mirror (used as a component of [DIALS](http://dials.github.io/)), maybe it's worth the while talking to Dave Mount and/or DIALS about how to proceed;
RxSpencer has a GitHub mirror (https://github.com/garyhouston/rxspencer).

**Comment by Chiel92** [comment]
> Sorry for a naive question, but why is there a need for 2 different XML parsers (expat and libxml)? As for other dependencies

Where did I mention libxml?

**Comment by ErwinJanssen** [comment]
Thanks for the overview @Chiel92.

* ANN is optional, it would be nice to have but it's not a priority.
* The current 32bit version is compiled by myself and I might be able to compile 64bit, but it would be preferable if libgd would publish an official release for Windows.
* `libtool` is quite important, this is used in the dynamic loading of the plug-ins used for the output and layout algorithms.
* RxSpencer is used as a drop-in regex replacement, since Windows doesn't come with `regex.h`. It is used in the core library `gvc`, so it's important to have either a 64bit of RxSpencer, or a different library that can be used as a drop-in replacement for `regex.h`

It looks like flexdll is Windows only and the API differs from libtool, so my preference would be to compile `libtool` for 64bit ourself and use that. The 32bit version was taken from [here](http://gnuwin32.sourceforge.net/packages/libtool.htm).

**Comment by twogee** [comment]
@Chiel92 sorry again, I was carried away by the discussion about gtk2 port.
@ErwinJanssen my point was that when other projects are on GitHub it's fairly easy to contribute Windows build support (nudge, nudge).

**Comment by ErwinJanssen** [comment]
Using other libraries with proper support and active development (and hosted on Github is also convenient) could be useful, I completely agree. But for the current case, quickly getting a 64bit build for Windows, it might be a too much hassle. As I understand it, people need a 64bit version as quickly as possible.

**Comment by twogee** [comment]
If you want it quick and dirty, why not try php_gd2.dll from http://phpdev.toolsforresearch.com/php-5.5.12-nts-Win32-VC11-x64.zip and cygltdl-7.dll from Cygwin? Still, no luck with RxSpencer... and, by the way, the latest versions on GitHub fix a couple of CVE vulns, one of them has score 6.8 :->

**Comment by chut89** [comment]
Things were easier when I installed msys2 and mingw-w64 on Windows. From msys command line, I could just type pacman -S mingw-w64-x86_64-rxspencer-alpha3.8.g6-2 and pacman -S libtool to install rxspencer and libtool, respectively without building them from source. 
@ErwinJanssen I did the trick to dump symbols from dlls and then created .lib files, upload here in case you need. I have rebuilt gvc project with no error.


[dependencies.zip](https://github.com/ellson/graphviz/files/907912/dependencies.zip)

**Comment by twogee** [comment]
👍 although I imagined that the goal was using VS rather than MinGW 😁

**Comment by chut89** [comment]
works well with VS, man. Would you mind testing them with VS and let me know if there's any problem?

**Comment by twogee** [comment]
I have no doubts about the usability; I was merely commenting on the uniformity of the build process.

**Comment by ErwinJanssen** [comment]
Using the libraries from @chut89, it does compile, but it doesn't work. When trying to generate a graph, it fails when loading the modules, so this version of ltdl doesn't seem to do the trick. I did include msys-2.0.dll when trying it.

**Comment by ellson** [comment]
Does running "dot -c" with installer privileges, generate <prefix>/lib64/graphviz/config6  ok?

This is the installation step where the capabiliies of all available plugins are scanned, so that later only the needed plugin is dynamically loaded.   Without running "dot -c" it will appear as if there are no plugins.

**Comment by chut89** [comment]
@ErwinJanssen Thank you for your try. Could you test it again placing `libltdl3.dll` in the same folder as `ltdl.lib`, in our case `$(SolutionDir)\windows\dependencies\libraries\lib`? I did not manage to compile `gvplugin_core` and `gvplugin_dot_layout` projects due to dllimport/export reason. Would you mind provide us the vcxproj files with x64 configuration? I will try setting them from 32 bit configuration.

**Comment by ErwinJanssen** [comment]
@chut89 I tried it with `libltdl3.dll` and `msys-2.0.dll` in the output directory of `gvc`, but that doesn't work.. If you have CMake, you can generate the x64 configuration using the generator `"Visual Studio 14 2015 Win64"`. Do you have this or should I provide them separately?

**Comment by chut89** [comment]
I have CMake already, but do you write one CMake file for the whole Graphviz project or do you mean I should write each CMake file for each individual project? I can only find CMake files in CMake folder from repository.

**Comment by ErwinJanssen** [comment]
There are already CMake files present. The best way to build is making a `build` directory in the project directory (so `$(ProjectDir)/build`), from there run `cmake -G "Visual Studio 14 2015 Win64" ..`, which will generate the Visual Studio project for x64 (assuming you use Visual Studio 2015).

**Comment by chut89** [comment]
Thank you very much for your work on `CMake`. After having `CMake` command run and `Graphviz` solution imported, I tried to build a minimal number of projects: `cdt`, `cgraph`, `dot`, `dotgen`, `gvc`, `gvplugin_core`, `gvplugin_dot_layout`, `pathplan`, `xdot` in order to test usability of `libtool`. So I put every binary and lib into output folder of `gvc` project, created a project named `gvc-test` that outputs an executable into that same folder. The test project merely creates a graph and layouts it. However, when I run the executable, it complained `Error: Layout type: "dot" not recognized. Use one of:` followed by emty line. 

As @ellson suggested running "dot -c", it gives me `Error: D:\Users\ha\bs\src\graphviz\build\lib\gvc\Release\config6 is zero sized, or other read error.  1 [main] dot 8668 D:\Users\ha\bs\src\graphviz\build\lib\gvc\Release\dot.exe: *** fatal error - Internal error: TP_NUM_C_BUFS too small: 50`

Have you got any idea what to proceed?

**Comment by Chiel92** [comment]
> There are already CMake files present. The best way to build is making a build directory in the project directory (so $(ProjectDir)/build), from there run cmake -G "Visual Studio 14 2015 Win64" .., which will generate the Visual Studio project for x64 (assuming you use Visual Studio 2015).

Do you mean `$(SolutionDir)` instead of `$(ProjectDir)`?

**Comment by Chiel92** [comment]
Side note: be sure to first `git clean` your repository before you use the cmake build infrastructure. Otherwise msbuild will use some generated .h files from the legacy msbuild infrastructure, resulting in compile errors.

**Comment by Chiel92** [comment]
Is it expected that the output directory of the dot project is `graphviz\build\cmd\dot\Debug\` and that it only contains `dot.exe` and not the dll dependencies?

**Comment by Chiel92** [comment]
When dropping in a msys-2.0.dll running dot in a mingw64 shell still gives a segmentation fault, but running it in a cmd shell gives 

```

C:\Users\Chiel.tenBrinke\Projects\graphviz\build\cmd\dot\Debug>type c:\Users\Chiel.tenBrinke\Desktop\maingraph.dot | .\dot.exe
      0 [main] dot 55948 C:\Users\Chiel.tenBrinke\Projects\graphviz\build\cmd\dot\Debug\dot.exe: *** fatal error - Internal error: TP_NUM_C_BUFS too small: 50
```

Similar to what @chut89 reported.

**Comment by magneticnorth** [comment]
This is very far outside my expertise, but note blog comments like http://www.experchange.com/what-is-tp_num_c_bufs-t4416339 <http://www.experchange.com/what-is-tp_num_c_bufs-t4416339>
as of about a year ago, asserting "obviously the regex_t type has the buggy undocumented “feature" that you can't safely define it as
an auto variable on the stack; it *must* be malloc'ed on the heap instead. I wish this factoid had made it into the GNU C-lib manual.
We have such code in gvusershape.c and gvconfig.c
Stephen

**Comment by Chiel92** [comment]
> We have such code in gvusershape.c and gvconfig.c

In order to avoid the whole regex lib thing, I commented out/replaced the code that uses regex.h in those two files to get something working as a start. 

See the latest two commits of https://github.com/Chiel92/graphviz/commits/64bit-dot at the time of writing.

So either I forgot something there, or the culprit is somewhere else.

**Comment by Chiel92** [comment]
When starting dot.exe from Visual Studio with a debugger attached using `c:\users\Chiel.tenbrinke\Desktop\maingraph.dot -Tsvg` as arguments, the program seems to hang at the line 186 in `gvplugin.c`.

That line says:
`    if (lt_dlinit()) {`

**Comment by Chiel92** [comment]
It strikes me that the legacy dot.vcxproj has more dependencies than the CMake generated one.
![image](https://cloud.githubusercontent.com/assets/1030961/25621602/24130cb6-2f52-11e7-948b-4c1f5547b43e.png)

vs 

![image](https://cloud.githubusercontent.com/assets/1030961/25621622/2e5a1872-2f52-11e7-81d8-21b56f15ca18.png)

Is that supposed to be?

**Comment by ErwinJanssen** [comment]
Ah yes, I did mean `$(SolutionDir)`, thanks for pointing that out.

As for placing all build artifacts into a single directory, running `cpack` in the build directory should take care of that. If you have NSIS installed, it will even generate a Windows installer, otherwise only a zip.

You break at the usage if libtool, which I feared would happen. Even when msys-2.0.dll is added, libtool still wouldn't work for me... This is the main blocker for 64bit Graphviz: a working 64bit version of libtool (ltdl.dll).

**Comment by Chiel92** [comment]
> You break at the usage if libtool, which I feared would happen. Even when msys-2.0.dll is added, libtool still wouldn't work for me... 

Yes, that seems to be correct. When I attach a debugger to dot.exe there is a segfault in `msys-2.0.dll`. We really seem to need a different ltdl implementation or something.

**Comment by graphviz** [comment]
Does anyone know for sure if GNU libtool even works on 64 bit windows?
I wasn’t able to find very much about this, which is a bit discouraging.

**Comment by Chiel92** [comment]
I haven't been able to compile libtool for 64 bit windows.

However, by manually calling LoadLibrary from` windows.h` I have managed to get a working version of `dot.exe` for 64 bit! 

It doesn't use rxspencer, and therefore can't generate config6 with the `-c` flag. You have to provide your own config6 file. The hacked source code can be found on this branch: https://github.com/Chiel92/graphviz/commits/64bit-dot

**Comment by ErwinJanssen** [comment]
That's very interesting! Are you able to generate graphs with this binary?

**Comment by Chiel92** [comment]
Yes, i've successfully generated svg exports.

**Comment by magneticnorth** [comment]
Nice!

Does this executable include the other layout engines like sfdp, neato, circo?

If so, can we just ifdef the code so Win64 doesn’t need libtool?

I thought we had brought in a different regex, and are hoping it works with Windows.

**Comment by twogee** [comment]
FWIW I mentioned `LoadLibrary` and 64 bit Cygwin previously...

**Comment by graphviz** [comment]
Yes, thank you. Does Cygwin have any downside here?

**Comment by ErwinJanssen** [comment]
@twogee Yes I remember you mentioned `LoadLibrary` and `flexdll`,. Do you know if `flexdll` support plugin discovery? Your Cygwin link slipped my mind, but I will check that out now.

Discovering plugins is also done with libtool at the moment, if we simply ìfdef` `dlopen` for `LoadLibrary`, that feature won't be supported on Windows any more, which means pre-generated config files...

**Comment by Chiel92** [comment]
> Discovering plugins is also done with libtool at the moment

What part of the code do you mean? I thought loading the dlls was the only thing we did with ldtl.

**Comment by twogee** [comment]
@graphviz Cygwin requires inclusion of cygwin dll just like MinGW needs msys dll. I suggested it as a quick way to get a working equivalent of ltdl, but I'd prefer a homogeneous toolchain.

@ErwinJanssen I scanned the code quickly, and the parts of ltdl API used are `lt_dlinit`, `lt_dlerror`, `lt_dlopen` and `lt_dlsym` .  Is it the last one that you call discovery? Windows equivalent of that would be `GetProcAddress`. The first two functions are purely administrative. Perhaps ifdef'ing would be easier than adding an extra layer of portability that feels somewhat superfluous anyway?

**Comment by Chiel92** [comment]
> Windows equivalent of that would be GetProcAddress

Indeed

https://github.com/Chiel92/graphviz/commit/42a4cfcaed4631f6f30cab98c61918007fc3e8ac

**Comment by ErwinJanssen** [comment]
Does #1243 resolve this issue?

**Comment by chut89** [comment]
> Does #1243 resolve this issue?> 

I tested it and it works perfectly. Before the ticket is closed, does anyone know why `libtool` does not work on Windows 64 bit?

**Comment by ErwinJanssen** [comment]
@chut89 A native Windows 64bit version of `libtool` could not be found, so at some point it was easier to just use a compatibility header and remove a dependency in the process. It might be possible to get `libtool` to work on 64bit, but it wasn't worth the hassle for me.

Anyway, it's good to hear that it's working!

**Comment by twogee** [comment]
`ltdl` is a Windows-specific portability library typically used by Cygwin or MinGW which need to emulate GNU dynamic linker. For all other purposes, ifdef is simpler.

**Comment by Chiel92** [comment]
The current code doesn't work for me out of the box. RxSpencer cannot be found. In the version I used until now, from https://github.com/ellson/graphviz/compare/master...Chiel92:64bit-dot, the code using regex.h had been worked around.

```
-- The following OPTIONAL packages have been found:

 * LTDL
 * ZLIB
 * PythonInterp

-- The following REQUIRED packages have been found:

 * AWK
 * BISON
 * FLEX
 * Git
 * Perl

-- The following OPTIONAL packages have not been found:

 * ANN
 * Cairo
 * EXPAT
 * GD
 * PangoCairo
 * NSIS

-- The following REQUIRED packages have not been found:

 * RxSpencer

CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FeatureSummary.cmake:556 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:170 (feature_summary)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RXSPENCER_LIBRARY (ADVANCED)
    linked by target "gvc" in directory C:/Users/Chiel.tenBrinke/Projects/graphviz/lib/gvc
```

**Comment by Chiel92** [comment]
In `cmd/dot/dot.vcxproj` I see that `ENABLE_LTDL` is defined. Should this be the case? I would expect not in the case of windows.

**Comment by ErwinJanssen** [comment]
Have you updated the contents of the git submodules, by running something like `git submodule update`? Otherwise the issue might be that your using Visual Studio 12 while most of the dependencies were compiled with Visual Studio 14... Something about different versions of the Visual C Redistributable i think.

`ENABLE_LTDL` means "enable dynamic loading" in the Graphviz code base, not necessarily that `ltdl` is used.

**Comment by Chiel92** [comment]
> Have you updated the contents of the git submodules, by running something like git submodule update? 

I did, but failed to notice that the command didn't work due to uncommitted changes. My bad.

Now the cmake command works properly. For Visual Studio 14 everything seems to work, but for Visual Studio 12 I get compile errors.

```
(Link target) ->
  gvdevice.obj : error LNK2019: unresolved external symbol snprintf referenced in function gvprintdouble [C:\Users\Chiel.tenBrinke\Projects\graphviz\build\lib\gvc\gvc.vcxproj]
  C:\Users\Chiel.tenBrinke\Projects\graphviz\build\lib\gvc\Debug\gvc.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\Chiel.tenBrinke\Projects\graphviz\build\lib\gvc\gvc.vcxproj]
```

The fact that most of the dependencies are compiled with 14 would indeed explain this. Maybe it's a good idea in general not to use a too new version, if it's not explicitly necessary. In my case, the graphviz dll's need to be able to run on certain versions of windows that are not supported by the Visual Studio 14 toolsets.

Anyway, I think we can close this issue, as the fundamental problem of compiling 64 bit for windows has essentially been solved!

**Comment by ErwinJanssen** [comment]
> The fact that most of the dependencies are compiled with 14 would indeed explain this. Maybe it's a good idea in general not to use a too new version, if it's not explicitly necessary. In my case, the graphviz dll's need to be able to run on certain versions of windows that are not supported by the Visual Studio 14 toolsets.

I agree, but third party libraries are provided as they are. Most dependencies could be downloaded from http://windows.php.net/downloads/ but only libraries for VS11, VS14 and sometimes VS15 are provided there.
