### ISSUE TITLE
Memory fault on simple graphj

### ISSUE THREAD

**Issue by emden** [ellson/graphviz#1225]
2.40.1 dot crashes on 

```c
digraph G  {
  a -> b
  {rank = sink c }
}
```
This works in 2.38. It also works if newrank=true.

The fault occurs during positioning, not ranking. The graph given to rank2 is not connected, though the new feasible_tree() routine explicitly requires this.

Interesting that the old network simplex worked with disconnected graphs.

**Comment by magneticnorth** [comment]
I think it would be worthwhile to replace all the positioning code with a
major overhaul
that would follow the pattern you already made of compiling the input graph
into another
graph that is solved, then applying the results to the original graph.
This could be more
modular than the existing design and get rid of some bugs.  Does Google
fund projects
like this?  I don't think I can stretch my consulting job to do encompass
this.

**Comment by emden** [comment]
Not sure, but this bug seems serious enough that it would be good to get 
a fix in before trying a major rewrite.
How did the old code construct a feasible tree with a disconnected 
graph? (In theory, the old code checked for a
disconnected graph and returned 1.)

If the new rank2 relies on having a connected graph as input, we should 
at least make sure this is what it is given.

Given that the crash happens in positioning, I was surprised that using 
newrank worked, since you would expect the same input.
It turns out this worked because newrank doesn't handle source, sink, 
etc. correctly, so the ranking is entirely different. I opened an issue 
on this.

**Comment by emden** [comment]
Fixed with revision fed9dd288d1e29e0ca0b1c9e2f800e91d5c78f4d.
