### ISSUE TITLE
OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by mandarup** [ellson/graphviz#1228]
System: MacOS
Python: 2.7.13 (brew)
graphviz (0.6)

code to reproduce error:

     $python 
     >>>import graphviz as gv
     >>>g = gv.Digraph(format='svg')
     >>>g.node('A')
     >>>g.node('B')
     >>>g.edge('A', 'B')
     >>>print(g.source)
      digraph {
    	A
    	B
    		A -> B
       }

      >>>g.render('g')

gives  error:

       ---------------------------------------------------------------------------
    OSError                                   Traceback (most recent call last)
    <ipython-input-21-252ffd7f8453> in <module>()
    ----> 1 g.render('g')

    .../lib/python2.7/site-packages/graphviz/files.pyc in render(self, filename, directory, view, cleanup)
        144         filepath = self.save(filename, directory)
        145 
    --> 146         rendered = backend.render(self._engine, self._format, filepath)
        147 
        148         if cleanup:

    .../lib/python2.7/site-packages/graphviz/backend.pyc in render(engine, format, filepath)
         93 
         94     try:
    ---> 95         subprocess.call(args, startupinfo=STARTUPINFO)
         96     except OSError as e:
         97         if e.errno == errno.ENOENT:

    /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in call(*popenargs, **kwargs)
        166     retcode = call(["ls", "-l"])
        167     """
    --> 168     return Popen(*popenargs, **kwargs).wait()
        169 
        170 

    /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
        388                                 p2cread, p2cwrite,
        389                                 c2pread, c2pwrite,
    --> 390                                 errread, errwrite)
        391         except Exception:
        392             # Preserve original exception in case os.close raises.

    /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
       1022                         raise
       1023                 child_exception = pickle.loads(data)
    -> 1024                 raise child_exception
       1025 
       1026 

    OSError: [Errno 20] Not a directory

This behavior was originally observed and reported at https://github.com/dmlc/xgboost/issues/2174

**Comment by magneticnorth** [comment]
This script works for me. Possibly your current directory is not writable.
I am not sure there is actually any graphviz bug here.

**Comment by mandarup** [comment]
i tried ``$chmod 777 <directory>`` , didn't help.

**Comment by twogee** [comment]
Errno 20 is POSIX `ENOTDIR`: python tries to pass wrong argument to a function call that expects a directory (like `rmdir()`). How does your `PATH` look like? Can you execute `dot` from command line?

**Comment by mandarup** [comment]
@twogee  ah that was it! ``brew install graphviz`` fixed it.  i had installed python package from ``pip`` ..
