### ISSUE TITLE
Undefined symbols in build, cannot compile

### ISSUE THREAD

**Issue by emprice** [ellson/graphviz#1230]
I am having trouble compiling `dot` on a Linux system. I get undefined symbols like `__log10_finite` and other similar math "_finite" variants. I am not sure where the problem originates. Google has been no help in isolating the issue. System details are below.

```
$ uname -a
Linux sabriel 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ErwinJanssen** [comment]
Which build system are you using to compile Graphviz? CMake or Autotools? Could you also include the error output?

**Comment by magneticnorth** [comment]
From random bits of fluff found on the internet, and emprice’s GitHub page, one suspects
there is a nonstandard copy of libm.so installed with Cython / python anaconda that does
not define that symbol, but some other library expects it.  I’m confused because I’m looking
on a Linux system and see that /usr/lib/libm.so resolves to other places like 
/usr/lib64/libmvec_nonshared.a /lib64/libmvec.so.1 neither of which has log10_finite
so at this point I’m stumped.

**Comment by emprice** [comment]
I'm using autotools. Error output below (omitting nominal output, there's just too much). I'm doing a local build with local tools because I do not have root privileges on this system, and much of the software is outdated.

```
$ CC=/home/eprice/bin/gcc-5.4 CXX=/home/eprice/bin/g++-5.4 ./configure --prefix=/home/eprice
... <omitted> ...
$ make -j8
... <omitted> ...
/home/eprice/bin/ld: skipping incompatible /home/eprice/lib/libgcc_s.so when searching for -lgcc_s
/home/eprice/bin/ld: skipping incompatible /home/eprice/lib/libgcc_s.so when searching for -lgcc_s
../../lib/gvc/.libs/libgvc.so: undefined reference to `__hypot_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__sqrt_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__exp_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__log2_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__atan2_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__acos_finite'
collect2: error: ld returned 1 exit status
make[3]: *** [dot] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/eprice/bin/ld: skipping incompatible /home/eprice/lib/libgcc_s.so when searching for -lgcc_s
/home/eprice/bin/ld: skipping incompatible /home/eprice/lib/libgcc_s.so when searching for -lgcc_s
../../lib/gvc/.libs/libgvc.so: undefined reference to `__exp_finite'
../../plugin/neato_layout/.libs/libgvplugin_neato_layout.so: undefined reference to `__pow_finite'
../../plugin/dot_layout/.libs/libgvplugin_dot_layout.so: undefined reference to `__hypot_finite'
../../plugin/neato_layout/.libs/libgvplugin_neato_layout.so: undefined reference to `__asin_finite'
../../plugin/core/.libs/libgvplugin_core.so: undefined reference to `__log10_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__acos_finite'
../../plugin/neato_layout/.libs/libgvplugin_neato_layout.so: undefined reference to `__sqrt_finite'
../../lib/gvc/.libs/libgvc.so: undefined reference to `__log2_finite'
../../plugin/neato_layout/.libs/libgvplugin_neato_layout.so: undefined reference to `__atan2_finite'
collect2: error: ld returned 1 exit status
make[3]: *** [dot_builtins] Error 1
make[3]: Leaving directory `/h/sabriel0/src/graphviz-2.40.1/cmd/dot'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/h/sabriel0/src/graphviz-2.40.1/cmd'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/h/sabriel0/src/graphviz-2.40.1'
make: *** [all] Error 2
```

**Comment by twogee** [comment]
I've seen suggestions to drop explicit linking with math library, ie `-lm`

**Comment by emprice** [comment]
So I'm chalking this up to a broken system. After nuking the whole thing and starting over, the problem seems to be gone. I was able to finally compile with the following command:

`LDFLAGS=-L/home/eprice/lib64 ./configure --prefix=/home/eprice --enable-perl=no --enable-r=no --enable-ruby=no --enable-tcl=no && make && make install`

**Comment by ellson** [comment]
Ellen,

Do you have some math libs in /home/eprice/libs ?

The build process looks first in <prefix>/lib/ so that you can override 
libs if you need to,  but on EL6 you shouldn't need anything non-standard.

Also, why do you need a non-standard gcc?

Perhaps try:  mkdir |/home/eprice/graphviz; ./||configure 
--prefix=/home/eprice/graphviz|

|
|

|John
|
