### ISSUE TITLE
Nodes wandering into subgraphs

### ISSUE THREAD

**Issue by conal** [ellson/graphviz#1232]
Is there a way to get dot to leave nodes in the graph in which they're declared rather than in some subgraph? In particular, I'm seeing that if the only outgoing edges for a given "source node" land in a subgraph, then the source node itself gets placed in that subgraph rather than the parent graph that declares the source node.

I stumbled onto a workaround: wrap *every* node in its own cluster subgraph. This practice somehow avoids the wandering node problem, but the resulting layouts are not as nice looking.

**Comment by emden** [comment]
Please provide a small example. Thanks.

**Comment by conal** [comment]
Take [wandering-node.dot.txt](https://github.com/ellson/graphviz/files/949073/wandering-node.dot.txt), remove the ".txt" extension, and invoke dot as

    dot -Tpdf -Gmargin=0 -Gsize=10,10 wandering-node.dot -o wandering-node.pdf

[Resulting PDF](https://github.com/ellson/graphviz/files/949067/wandering-node.pdf).

Now make each node its own cluster subgraph, resulting in [no-wandering-node.dot.txt](https://github.com/ellson/graphviz/files/949077/no-wandering-node.dot.txt), remove the ".txt" extension, and invoke dot as

    dot -Tpdf -Gmargin=0 -Gsize=10,10 no-wandering-node.dot -o no-wandering-node.pdf

[Resulting PDF](https://github.com/ellson/graphviz/files/949078/no-wandering-node.pdf).

**Comment by emden** [comment]
There is a restriction on graphs that says if an edge is in a cluster, its endpoints are also in the cluster. (In the Lexical and Semantic Notes section of the [dot language](http://www.graphviz.org/content/dot-language), there is the note

> If an edge belongs to a cluster, its endpoints belong to that cluster. Thus, where you put an edge can effect a layout, as clusters are sometimes laid out recursively.

 )

This makes sense if you consider an edge to be an ordered pair of nodes. So either a node goes into the edge's cluster or the edge is moved out. If you use -Tdot on your no-wandering graph, you'll see that the edge has been moved out of the cluster.

**Comment by conal** [comment]
Thanks for the explanation. Closing the issue.
