### ISSUE TITLE
Building graphviz from source on Ubuntu (to add gts triangulation library)

### ISSUE THREAD

**Issue by josephrocca** [ellson/graphviz#1237]
When installing on ubuntu (16.04.2) with `sudo apt install graphviz`, I get the following error when trying to use `sfdp`:

```
Error: remove_overlap: Graphviz not built with triangulation library
```
After some searching I found out that it's because graphviz was built with `--without-gts` ([launchpad bug report](https://bugs.launchpad.net/ubuntu/+source/graphviz/+bug/1409280)). So I set about trying to build it myself (I'm new to this).

I followed the following procedure (from [this SO answer](http://stackoverflow.com/questions/34228395/ubuntu-graphviz-sfdp-not-working/42579735)):

1. run `sudo apt install libgts-dev`
2. run `sudo pkg-config --libs gts`
3. run `sudo pkg-config --cflags gts`
4. Download `graphviz-2.40.1.tar.gz` from [here](http://www.graphviz.org/Download_source.php)
5. Extract and run `sudo ./configure --with-gts  --prefix ~` in the folder
6. Run `sudo make` in the folder
7. Run `sudo make install` in the folder

After doing that I can successfully use some commands (dot, fdp), but not others (sfdp, neato). I get `/usr/bin/sfdp: No such file or directory` when trying to use `sfdp`, for example. Can anyone see anything wrong with my procedure? Thanks!

**Comment by josephrocca** [comment]
I'm not sure what I did, but I somehow got it working (at least, all looks good so far). For others having this problem, try:

* Restarting your computer
* Before installing, making sure you've ran `sudo apt purge graphviz` (and `sudo make uninstall` if you're retrying building from source)
* Make sure you're using `sudo` for installing
* Have a look at the output of `sudo ./configure --with-gts --prefix ~` - at the end it'll tell you which commands/options are available given the dependencies that you have.

Good luck!

**Comment by graphviz** [comment]
Hi - in case it helps, I’ll add that I routinely build graphviz using my own 
non-privileged user ID and install in my home directory.

Most (all) of the external packages graphviz needs are installed in /usr/local
in my case using Mac homebrew.  XQuartz is installed too.

The configure looks like
CC=clang CXX=clang++ AR=/usr/bin/ar LIBTOOL=glibtool ./configure CFLAGS='-Wl,-no_pie -g -O0 ' CXXFLAGS='-Wl,-no_pie -g -O0' --with-extralibdir=/usr/local/opt/gettext/lib --with-extraincludedir=/usr/local/opt/gettext/include --prefix=/Users/north --with-cairopango --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib --with-ann=yes  --disable-php --enable-static

Some of this may be superfluous but it works.  I think there  the Xcode based tools like clang
and the GNU based tools like glibtool do not see totally eye-to-eye.

If you are having problems with this, maybe there is something in an environment variable like PATH or CFLAGS that
is pointing to the wrong copy of some package that was previously installed.  In my case I already have another
copy of graphviz installed via homebrew that doesn’t interfere with my personal build.

Stephen North

**Comment by dustinmichels** [comment]
This thread was very helpful to me! For anyone else having trouble, I'll just note that my exact steps were:

1. Remove any existing installation with `conda uninstall graphviz`. (If you did not install with Conda, you might need to do `sudo apt purge graphviz` and/or `pip uninstall graphviz`).
2. run `sudo apt install libgts-dev`
3. run `sudo pkg-config --libs gts`
4. run `sudo pkg-config --cflags gts`
5. Download graphviz-2.40.1.tar.gz from [here](http://www.graphviz.org/Download_source.php)
6. Navigate to directory containing download, and extract with `tar -xvf graphviz-2.40.1.tar.gz` (or newer whatever the download is named.)
7. `cd` into extracted folder (ie `cd graphviz-2.40.1`) and run` sudo ./configure --with-gts`
8. Run `sudo make` in the folder
9. Run `sudo make install` in the folder
10. Reinstall library using `pip install graphviz`

**Comment by blaiseli** [comment]
@dustinmichels What are the `pkg-config` commands for?

**Comment by ellson** [comment]
pkg-config is a facility for getting info, during make of my package, about the CFLAGS and LIBS required to include headers and link to another packages libs.

packages that provide shared libraries that are intended for use by other projects should provide pkg-config info.

pks-config info is stored in *.pc files in a well-known place (on Fedora: /usr/lib64/pkgconfig ) or anywhere in a PHG-CONFIG-PATH
