### ISSUE TITLE
labelfontsize is ignored

### ISSUE THREAD

**Issue by daveloyall** [ellson/graphviz#1238]
They say a picture is worth 1000 words.

This graph...

    digraph g {
        a -> b [label="test",labelfontsize="40"];
        b [fontsize="40"];
    }

...compiled like this...

    $ dot -Tpng -o DONUTS-TMP.png DONUTS-TMP.dot

...produces this output.
![image](https://cloud.githubusercontent.com/assets/1524866/25829829/81a64566-341e-11e7-8849-65978cbdb505.png)

I am using this dot:

    $ dot -V
    dot - graphviz version 2.41.20170503.1600 (20170503.1600)

Which I built myself on a 64bit debian machine using https://github.com/ellson/graphviz/commit/1bf033d2979b07416c4f42e09b90db133d88b877.

For what it is worth, `labelangle` and `labeldistance` don't seem to work either.

**Comment by daveloyall** [comment]
Sorry for the extra pixels on the screen shot.  Assume an ordinary PNG file with no border, please!

**Comment by magneticnorth** [comment]
> On May 8, 2017, at 7:53 PM, Dave Loyall <notifications@github.com> wrote:
> 
> digraph g {
>     a -> b [label="test",labelfontsize="40"];
>     b [fontsize="40"];
> }

Sorry there is a misunderstanding. labelfontsize refers only to headlabel or taillabel as mentioned in
http://www.graphviz.org/doc/info/attrs.html#d:labelfontsize <http://www.graphviz.org/doc/info/attrs.html#d:labelfontsize>

You might want instead just       a -> b [label=“test”, fontsize="40"];

**Comment by daveloyall** [comment]
Thanks!

![image](https://cloud.githubusercontent.com/assets/1524866/25860475/443ef50e-34a7-11e7-9646-02a07b73dd67.png)
