### ISSUE TITLE
[Dot] Output format plain edges wrong

### ISSUE THREAD

**Issue by yss14** [ellson/graphviz#1248]
My input dot file
```
digraph{rankdir="LR";node[shape=box;width=3.5;height=3.5];101 -> {105};105 -> {106};106 -> {105};299011936 -> {101}}
```
If I choose svg or jpg as output format, the graph looks fine.
If I choose plain as output format, the edge's positions seems wrong.
```
graph 1 15.5 3.5
node 101 5.75 1.75 3.5 3.5 101 solid box black lightgrey
node 105 9.75 1.75 3.5 3.5 105 solid box black lightgrey
node 106 13.75 1.75 3.5 3.5 106 solid box black lightgrey
node 299011936 1.75 1.75 3.5 3.5 299011936 solid box black lightgrey
edge 101 105 4 7.5004 1.75 7.6189 1.75 7.7387 1.75 7.8579 1.75 solid black
edge 105 106 4 11.5 1.6569 11.619 1.6563 11.739 1.6561 11.858 1.6564 solid black
edge 106 105 4 11.998 1.8431 11.879 1.8437 11.759 1.8439 11.64 1.8436 solid black
edge 299011936 101 4 3.5004 1.75 3.6189 1.75 3.7387 1.75 3.8579 1.75 solid black
stop
```
Example:
```
node 299011936 1.75 1.75 3.5 3.5 299011936 solid box black lightgrey
```
It says that `x` starts at 1.75 and the rect is 3.5 inches long. So there should be an edge starting at x=5.25, right? But there isn't... Or is my interpretation of the output format wrong?

This is the output as jpg:
![test](https://user-images.githubusercontent.com/4346842/27262664-e24683d8-545b-11e7-85bc-adc2fd47ca59.jpg)

**Comment by Pike** [comment]
The numbers match better assuming that the coordinates for the boxes are their centers.

**Comment by yss14** [comment]
Thanks man for that hint, you saved me from writing a svg parser! You are right, it totally makes sense now! This should be mentioned in the [output format docs](http://www.graphviz.org/doc/info/output.html#d:plain).
