### ISSUE TITLE
In recent versions, some edges in dot are routed through nodes

### ISSUE THREAD

**Issue by fedarko** [ellson/graphviz#1255]
Hi,

I've noticed a bug in recent versions of Graphviz where certain edges are being routed through nodes, even in cases where a more optimal (without any edge-node-crossings) routing seems to be available.

This error seems to have been introduced some time after version 2.38.0 of Graphviz, since that version produces desirable edge routings for me while more recent versions (the oldest version I've observed with this problem is version 2.39.20160727.0821, but I haven't done a lot of testing on versions) produce "undesirable" edge routings.

For reference, I've enclosed the DOT file for a graph which exhibits this problem at the end of this post.
Running `dot` (Graphviz version 2.39.20160727.0821) on the enclosed graph produces the following drawing, with edge crossings through nodes c_B20_142_198_17, -35, 206, and -4:
<img src="https://user-images.githubusercontent.com/4177727/27998807-e4a55950-64e2-11e7-94cc-3a8ff7ddaf72.png" width=200 />

Running `dot` (Graphviz version 2.38.0) on the enclosed graph, however, produces the following (with no edge-node crossings) drawing:
<img src="https://user-images.githubusercontent.com/4177727/27998808-f1121a2a-64e2-11e7-8eea-91d2ece8a2bd.png" width=200 />

Here's the graph used to generate these images.

```
digraph asm {
	edge [headport=n,tailport=s];
	c_B20_142_198_17 [height=9.73611,width=3.125,shape=rectangle];
	c_Bc40_c156_c69_65 [height=9.63889,width=3.125,shape=rectangle];
	-35 [height=1.43136,width=1.1964,shape=house];
	-4 [height=4.74461,width=2.17821,shape=house];
	-199 [height=1.36173,width=1.16693,shape=house];
	-200 [height=1,width=1,shape=house];
	-201 [height=1,width=1,shape=house];
	206 [height=1.25527,width=1.12039,shape=invhouse];
	-158 [height=1,width=1,shape=house];
	-159 [height=2.03743,width=1.42738,shape=house];
	41 [height=2.5302,width=1.59066,shape=invhouse];
	259 [height=1,width=1,shape=invhouse];
	-127 [height=2.03342,width=1.42598,shape=house];
	-61 [height=1.77085,width=1.33073,shape=house];
	-62 [height=2.04532,width=1.43015,shape=house];
	207 [height=1.11394,width=1.05544,shape=invhouse];
	-279 [height=1.54407,width=1.24261,shape=house];
	-63 [height=3.24527,width=1.80146,shape=house];
	-35 -> c_B20_142_198_17
	-35 -> -63
	c_B20_142_198_17 -> -35
	-4 -> -35
	-199 -> -4
	-199 -> -279
	-200 -> -199
	-200 -> 207
	-201 -> -62
	-201 -> -200
	206 -> -201
	c_Bc40_c156_c69_65 -> 206
	-158 -> c_Bc40_c156_c69_65
	-159 -> -158
	41 -> -158
	259 -> 41
	259 -> -127
	-127 -> c_Bc40_c156_c69_65
	-61 -> -201
	-62 -> -61
	207 -> 206
	-279 -> -61
	-63 -> -159
	-63 -> 259
}
```

Thanks!

**Comment by ellson** [comment]
This problem was introduced in commit 0f82197c80980b96ac00633b5c5852a4c9abc3cd by Emden on 2014-09-01 14:49:59   "Remove old hacks used when coordintes were integers. "

**Comment by ellson** [comment]
(Incidentally, to build that commit on a modern Linux, use:  --without-ghostscript --disable-php --disable-ocam)

**Comment by ellson** [comment]
Emden,


Is it possible that these hacks were nothing to do with coordinates being integers,  but more to ensure that the first point of an edge was at least 1 point away from the endpoint in a reasonable direction?


I'm thinking that the change should probably just be reverted (but with some commentary added)  ?


John

**Comment by emden** [comment]
Yes, revert the code. I don't believe I would have gone to this trouble unless these adjustments were causing a problem, but since I didn't document what the problem might have been, let's go back.

**Comment by ellson** [comment]
Done.  Change should be in tonight's snapshot builds.

This may break some regression tests.

**Comment by fedarko** [comment]
The snapshot build works well for me. Thank you so much!
