### ISSUE TITLE
conflicting declaration ‘typedef long long int int64_t’ from includes in gv_ocaml.cpp prevents building

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ellson/graphviz#1262]
Ubuntu 17.04
git commit 9eee865
libc6-dev           2.24-9ubuntu2.2
libstdc++-6-dev 6.3.0-12ubuntu2

Building with:
```
./autogen.sh NOCONFIG
./configure   --build=x86_64-pc-linux-gnu \
              --prefix=/usr --sysconfdir=/etc --localstatedir=/var
make dist
```
leads to:
```
...
swig -c++ -ocaml -o gv_ocaml.cpp ./gv.i
mv gv_ocaml.cpp gv_ocaml.cpp.orig
sed '/int caml_array_length/d' gv_ocaml.cpp.orig > gv_ocaml.cpp
rm gv_ocaml.cpp.orig
  CXX      libgv_ocaml_la-gv_ocaml.lo
<command-line>:0:7: error: conflicting declaration ‘typedef long long int int64_t’
In file included from /usr/include/stdlib.h:275:0,
                 from /usr/include/c++/6/cstdlib:75,
                 from /usr/include/c++/6/stdlib.h:36,
                 from gv_ocaml.cpp:750:
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: previous declaration as ‘typedef long int int64_t’
 __intN_t (64, __DI__);
 ^
Makefile:2152: recipe for target 'libgv_ocaml_la-gv_ocaml.lo' failed
make[4]: *** [libgv_ocaml_la-gv_ocaml.lo] Error 1
make[4]: Leaving directory '/home/actionmystique/src/Topology/git-graphviz/tclpkg/gv'
Makefile:2683: recipe for target 'install-recursive' failed
...
```

**Comment by ellson** [comment]
This looks like a problem between two Ubuntu standard header files. I think between:
    /usr/include/types.h
and
   /usr/include/x86_64-linux-gnu/sys/types.h

I don't see this issue on Fedora.  Could you try reporting this to Ubuntu please?

**Comment by jean-christophe-manciot** [comment]
There is no such file as ```/usr/include/types.h```.
However, since the error message means that the ```typedef long long int int64_t``` declaration within /usr/include/x86_64-linux-gnu/sys/types.h which is included by other files is conflicting with another ```int64_t``` declaration, I searched where such a conflicting declaration could be located in graphviz code:

```
root@samsung-ubuntu:/home/actionmystique/src/Topology# grep -rP "typedef .* int64_t" *
git-graphviz/windows/include/unistd.h:typedef __int64           int64_t;
git-graphviz/windows/dependencies/libraries/x86/include/gdk/glext/glxext.h:typedef Bool ( * PFNGLXGETSYNCVALUESOMLPROC) (Display *dpy, GLXDrawable drawable, int64_t *ust, int64_t *msc, int64_t *sbc);
git-graphviz/windows/dependencies/libraries/x86/include/gdk/glext/glxext.h:typedef int64_t ( * PFNGLXSWAPBUFFERSMSCOMLPROC) (Display *dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder);
git-graphviz/windows/dependencies/libraries/x86/include/gdk/glext/glxext.h:typedef Bool ( * PFNGLXWAITFORMSCOMLPROC) (Display *dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder, int64_t *ust, int64_t *msc, int64_t *sbc);
git-graphviz/windows/dependencies/libraries/x86/include/gdk/glext/glxext.h:typedef Bool ( * PFNGLXWAITFORSBCOMLPROC) (Display *dpy, GLXDrawable drawable, int64_t target_sbc, int64_t *ust, int64_t *msc, int64_t *sbc);
git-graphviz/windows/dependencies/libraries/x86/include/pixman.h:typedef __int64 int64_t;
git-graphviz/windows/dependencies/libraries/x86/include/harfbuzz/hb-common.h:typedef __int64 int64_t;
git-graphviz/windows/dependencies/libraries/x64/include/pixman.h:typedef __int64 int64_t;
git-graphviz/windows/dependencies/libraries/x64/include/harfbuzz/hb-common.h:typedef __int64 int64_t;
git-graphviz/dependencies/criterion/dependencies/nanopb/extra/pb_syshdr.h:typedef signed long long int64_t;
```

It seems that the conflict resides in your code instead.

**Comment by twogee** [comment]
The error message states that `‘typedef long long int int64_t’` conflicts with `‘typedef long int int64_t’`; those are not among the declarations found by `grep`.

**Comment by magneticnorth** [comment]
But you're concerned with building under ubuntu.

I don't think a windows compatibility shim or criterion (a testing
framework) have anything to do with it.

In the past we have found swig is a moving target and sometimes does not
track the very latest versions
of some of the compilers it supports. You may have to turn off swig or some
of the specific language APIs.

just a hunch anyway
Stephen

**Comment by twogee** [comment]
Some of `int64_t` matches in the above are irrelevant, all type declarations but nano protocol buffers (used by criterion) use `__int64` (i.e. they defer to whatever internal definition is provided by the platform). And, as @magneticnorth stated, none are relevant to the error above. Most probably, code generated by swig causes the collisions between type definitions in standard headers (could you please run your `grep` command on them as well?)

**Comment by twogee** [comment]
I believe the cryptic message `<command-line>:0:7: error: conflicting declaration` is the key,which leads straight to (the well concealed) `CPPFLAGS = -Dint64=int64_t`

**Comment by ellson** [comment]
I pushed a fix that adds "#include <stdint.h>" to the generated gv_ocaml.cpp.

Doesn't seem to break the Fedora build.  Please let me know if it helps on Ubuntu?

**Comment by jean-christophe-manciot** [comment]
No: with git commit 20170804.28819d4, I get the exact same compilation error.

**Comment by twogee** [comment]
I believe the extra define in line

`libgv_ocaml_la_CPPFLAGS = $(BASECPPFLAGS) $(OCAML_INCLUDES) -Dint64=int64_t`

can be left out. Then libgv_ocaml_la-gv_ocaml.o compiles. Maybe it's something specific to preprocessor in GCC 6.

**Comment by ellson** [comment]
If I do that on Fedora I get many errors like:
    gv_ocaml.cpp: In function ‘void caml_print_val(caml_value_t)’:
    gv_ocaml.cpp:845:31: error: ‘int64’ was not declared in this scope
     #define SWIG_Int64_val(v) (*((int64 *) SWIG_Data_custom_val(v)))
                                                           ^
Does Ubuntu have swig >= 1.3.40 ?

I tried:
    -Dint64="long long"
on Fedora, and that seemed to work.  Can you try that on Ubuntu?

**Comment by twogee** [comment]
Ubuntu 17.04 has Swig 3.0.10; "long long" (or just "long") yields

```
<command-line>:0:7: error: 'long long long' is too long for GCC
```
😞

**Comment by graphviz** [comment]
Is it important to have graphviz for OCAML?  The graphviz project does not seem to be in
a good position to get help for the swig interface to OCAML on various platforms.  Maybe
just disable ocaml for now and see if the situation ever improves?

**Comment by twogee** [comment]
There seem to be 2 instances where `int64` is used

```
#define SWIG_Int64_val(v) (*((int64 *) SWIG_Data_custom_val(v)))
CAMLextern int64 Int64_val(caml_value_t v);
```
Because gc_ocaml.cpp is run through sed, maybe the type definition could be hacked in like

`sed '/int caml_array_length/d;s/\([^_]\)int64 /\1int64_t /' gv_ocaml.cpp.orig > gv_ocaml.cpp`

**Comment by jean-christophe-manciot** [comment]
@graphviz Fair question. 
Graphviz compiles successfully if ocaml is left out with:
```
./configure --enable-ocaml=no \
...
```
