### ISSUE TITLE
testsuite: which of the ksh implementations is known to be able to run rtest.sh?

### ISSUE THREAD

**Issue by ng-0** [ellson/graphviz#1267]
Hi,

one of our good usage policies is that we run test suites whenever possible, whereever possible with
applications.
mksh seemed like the shell which would be able to run this script, however it fails the check.
Could you tell me which exact shell (name, binary-name and version) you use to run this test?

I know it is "ksh93", but which available free software implementation, if any, is able to run it.

Thanks!

edit: is it really just the original ksh-93 as available from here https://github.com/att/ast ?

**Comment by ellson** [comment]
I'm not sure what script you are running, is it rtest/rtest.sh >
Any real ksh should work.  e.g on Fedora-26 I have:
      ksh-20120801-35.fc26.x86_64
which identifies itself as:
    $ ksh --version
        version         sh (AT&T Research) 93u+ 2012-08-01

I've no idea about building ksh from the github sources.   I get my ksh as a binary from Fedora or Centos distributions.

**Comment by ng-0** [comment]
> I'm not sure what script you are running, is it rtest/rtest.sh ?

Exactly this one (that's the one your "make check" phase uses).

Well "any real ksh" is difficult as there's mksh, oksh, loksh, ...

>     version         sh (AT&T Research) 93u+ 2012-08-01

...and I have just started to package the original ksh-93 (which the ksh you quoted is) to check if it works for the testsuite.
I haven't checked all of its licenses but it seems separated from the usual AT&T proprietary licenses.

I'll re-open this ticket if ksh-93 (from recent HEAD of its source) isn't working with the testsuite aswell.

Thanks!
