### ISSUE TITLE
CGraph: Is there a way to convert a directed graph to an undirected graph?

### ISSUE THREAD

**Issue by Chiel92** [ellson/graphviz#1274]
Looking at the cgraph.h interface, it seems that only when creating a graph, properties such as directedness and strictness can be specified. 

Once we have a directed `Agraph_t`, what is the easiest way to make it undirected?

**Comment by emden** [comment]
This is just stored as a bit in g->desc.directed. Setting this to 0 should do it. Technically, if there are subgraphs, each of them would also have to be reset as well, though I can't recall anyplace that checks for directedness in a subgraph.

**Comment by Chiel92** [comment]
Thanks for the swift response! Good to know that it's actually that easy.

**Comment by magneticnorth** [comment]
"Beware of bugs in the above code; I have only proved it correct, not tried it.”  - Donald Knuth, 1977.

**Comment by ellson** [comment]
You could also code all your graphs as undirected (using "--" for all edges)  and then run it through dot if you want it to be interpreted as directed.   Dot will infer -> edges unambiguously based on the linear ordering of nodes in the input text.

**Comment by ellson** [comment]
If you want to show arrowheads in your output,  you can use "dot -Edir=forward"
$ echo "graph{a--b}" | dot -Edir=forward -Tpng >test.png

![test](https://user-images.githubusercontent.com/1512253/29667545-c74e52da-88aa-11e7-930b-ea359e23390f.png)
