### ISSUE TITLE
Embedded SVG

### ISSUE THREAD

**Issue by jdtempleton** [ellson/graphviz#1294]
Hello, I am hoping someone can either tell me what I am doing wrong and/or point me in the right direction. I am trying to take a dot file which for some of it's nodes are paths to SVG images and convert it to one SVG image. I am working off some legacy code I am updating which use to do this by using the svg:cairo plugin with the command: ```dot -Tsvg:cairo input.dot -o output.svg``` Whenever I run this command now in the new environment, I get an error message which says, 'Warning: No loadimage plugin for "svg:cairo"'. I have also tried the command ```dot -Tsvg input.dot -o output.svg```, but this does not produced the desired results because it doesn't embed the SVG content into the output.svg. It only defines the path to the file of the SVGs. I have tried searching through both Graphviz and Cairo Documentation to find some information, but neither have produced any help.

I am running this on a Debian Stretch OS and I have installed:

* libcairo2
* libcairo2-dev
* libpangocairo-1.0-0
* graphviz
* graphviz-dev
* libgraphviz-dev

Example dot file:

```
graph G {
	graph [
		splines=false forcelabels=true  dpi=72
	];
	node [
		shape="none" fontname=Helvetica labelfontsize=12 forcelabels="true";
		label="none" size=50 fixedsize="true" scale="true"
	];
	edge [
		labelfontsize=12 fontname=Helvetica labeldistance=1.2 labelangle = 320.0
	];
	rankdir=RL
	nodesep="0.01" ;
	0 [
		shape=box label="OH"
	]
	1 [
		label="" image="/programs/gw_misc/SNFG/V1/DManp.svg" height="0.7"
	]
	0--1 [
		headlabel="a"
	]
}
```

Resulting SVG from ```dot -Tsvg input.dot -o output.svg```:

Note: The path in the image tag.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)-->
<!-- Title: G Pages: 1 -->
<svg width="152pt" height="58pt" viewBox="0.00 0.00 152.00 58.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 54)">
		<title>G</title>
		<polygon fill="white" stroke="none" points="-4,4 -4,-54 148,-54 148,4 -4,4"/>
		<!-- 0 -->
		<g id="node1" class="node"><title>0</title>
			<polygon fill="none" stroke="black" points="144,-43 90,-43 90,-7 144,-7 144,-43"/>
			<text text-anchor="middle" x="117" y="-21.3" font-family="Helvetica,sans-Serif" font-size="14.00">OH</text>
		</g>
		<!-- 1 -->
		<g id="node2" class="node"><title>1</title>
			<image xlink:href="/programs/gw_misc/SNFG/V1/DManp.svg" width="54px" height="50px" preserveAspectRatio="xMinYMin meet" x="0" y="-50"/>
		</g>
		<!-- 0&#45;&#45;1 -->
		<g id="edge1" class="edge"><title>0&#45;&#45;1</title>
			<path fill="none" stroke="black" d="M89.5971,-25C78.3579,-25 65.2848,-25 54.081,-25"/>
			<text text-anchor="middle" x="63.2735" y="-29.6135" font-family="Helvetica,sans-Serif" font-size="12.00">a</text>
		</g>
	</g>
</svg>
```

Example of what I need to get and was the result from an older machine running ```dot -Tsvg:cairo input.dot -o output.svg```

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="152pt" height="58pt" viewBox="0 0 152 58" version="1.1">
    <defs>
    <g>
        <symbol overflow="visible" id="glyph0-0">
            <path style="stroke:none;" d="M 1 2 L 1 -10 L 8 -10 L 8 2 Z M 2 1 L 7 1 L 7 -9 L 2 -9 Z M 2 1 "/>
        </symbol>
        <symbol overflow="visible" id="glyph0-1">
            <path style="stroke:none;" d="M 5.5 -9 C 4.425781 -9 3.570312 -8.640625 2.9375 -7.921875 C 2.3125 -7.203125 2 -6.226562 2 -5 C 2 -3.769531 2.3125 -2.796875 2.9375 -2.078125 C 3.570312 -1.359375 4.425781 -1 5.5 -1 C 6.582031 -1 7.4375 -1.359375 8.0625 -2.078125 C 8.6875 -2.796875 9 -3.769531 9 -5 C 9 -6.226562 8.6875 -7.203125 8.0625 -7.921875 C 7.4375 -8.640625 6.582031 -9 5.5 -9 Z M 5.5 -10 C 6.863281 -10 7.953125 -9.546875 8.765625 -8.640625 C 9.585938 -7.734375 10 -6.519531 10 -5 C 10 -3.476562 9.585938 -2.265625 8.765625 -1.359375 C 7.953125 -0.453125 6.863281 0 5.5 0 C 4.132812 0 3.039062 -0.453125 2.21875 -1.359375 C 1.40625 -2.265625 1 -3.476562 1 -5 C 1 -6.519531 1.40625 -7.734375 2.21875 -8.640625 C 3.039062 -9.546875 4.132812 -10 5.5 -10 Z M 5.5 -10 "/>
        </symbol>
        <symbol overflow="visible" id="glyph0-2">
            <path style="stroke:none;" d="M 1 -10 L 2 -10 L 2 -6 L 8 -6 L 8 -10 L 9 -10 L 9 0 L 8 0 L 8 -5 L 2 -5 L 2 0 L 1 0 Z M 1 -10 "/>
        </symbol>
        <symbol overflow="visible" id="glyph1-0">
            <path style="stroke:none;" d="M 1 3 L 1 -8 L 7 -8 L 7 3 Z M 2 2 L 6 2 L 6 -7 L 2 -7 Z M 2 2 "/>
        </symbol>
        <symbol overflow="visible" id="glyph1-1">
            <path style="stroke:none;" d="M 4.734375 -3 C 3.703125 -3 2.988281 -2.921875 2.59375 -2.765625 C 2.195312 -2.609375 2 -2.34375 2 -1.96875 C 2 -1.675781 2.144531 -1.441406 2.4375 -1.265625 C 2.738281 -1.085938 3.144531 -1 3.65625 -1 C 4.363281 -1 4.929688 -1.160156 5.359375 -1.484375 C 5.785156 -1.816406 6 -2.253906 6 -2.796875 L 6 -3 Z M 7 -3.53125 L 7 0 L 6 0 L 6 -1 C 5.726562 -0.65625 5.382812 -0.398438 4.96875 -0.234375 C 4.5625 -0.078125 4.054688 0 3.453125 0 C 2.703125 0 2.101562 -0.171875 1.65625 -0.515625 C 1.21875 -0.867188 1 -1.335938 1 -1.921875 C 1 -2.609375 1.265625 -3.125 1.796875 -3.46875 C 2.335938 -3.820312 3.144531 -4 4.21875 -4 L 6 -4 L 6 -4.1875 C 6 -4.757812 5.832031 -5.203125 5.5 -5.515625 C 5.175781 -5.835938 4.71875 -6 4.125 -6 C 3.082031 -6 2.382812 -5.832031 2.03125 -5.5 C 1.675781 -5.164062 1.332031 -5 1 -5 L 1 -6 C 1.382812 -6 1.757812 -6.164062 2.125 -6.5 C 2.5 -6.832031 3.191406 -7 4.203125 -7 C 5.140625 -7 5.835938 -6.710938 6.296875 -6.140625 C 6.765625 -5.566406 7 -4.695312 7 -3.53125 Z M 7 -3.53125 "/>
        </symbol>
    </g>
    </defs>
    <g id="surface1">
        <rect x="0" y="0" width="152" height="58" style="fill:rgb(100%,100%,100%);fill-opacity:1;stroke:none;"/>
        <path style="fill:none;stroke-width:1;stroke-linecap:butt;stroke-linejoin:miter;stroke:rgb(0%,0%,0%);stroke-opacity:1;stroke-miterlimit:10;" d="M 144 -43 L 90 -43 L 90 -7 L 144 -7 Z M 144 -43 " transform="matrix(1,0,0,1,4,54)"/>
        <g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
          <use xlink:href="#glyph0-1" x="110" y="32.699219"/>
          <use xlink:href="#glyph0-2" x="121.25" y="32.699219"/>
        </g>
        <path style="fill-rule:nonzero;fill:rgb(0%,78.431373%,19.607843%);fill-opacity:1;stroke-width:25;stroke-linecap:butt;stroke-linejoin:miter;stroke:rgb(0%,0%,0%);stroke-opacity:1;stroke-miterlimit:4;" d="M 575.720958 345.919647 C 575.720958 449.698388 491.601103 533.785778 387.857146 533.785778 C 284.11319 533.785778 199.993334 449.698388 199.993334 345.919647 C 199.993334 242.172212 284.11319 158.084822 387.857146 158.084822 C 491.601103 158.084822 575.720958 242.172212 575.720958 345.919647 Z M 575.720958 345.919647 " transform="matrix(0.134759,0,0,0.124777,-21.267379,-14.162878)"/>
        <path style="fill:none;stroke-width:1;stroke-linecap:butt;stroke-linejoin:miter;stroke:rgb(0%,0%,0%);stroke-opacity:1;stroke-miterlimit:10;" d="M 89.597656 -25 C 78.359375 -25 65.285156 -25 54.082031 -25 " transform="matrix(1,0,0,1,4,54)"/>
        <g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
          <use xlink:href="#glyph1-1" x="63.773438" y="24.386719"/>
        </g>
    </g>
</svg>
```

**Comment by magneticnorth** [comment]
You are getting deep into code that we haven’t thought much about in years, but
I recall graphviz needs libexpat and librsvg at build time for that to work. You
could look in config.log and see if they are enabled so plugin/rsvg is being built.
(You are building your own copy of graphviz locally?)

Also, I wonder about other tools to “transpile” SVG, such as
svg-inline-loader that you can run under node.
https://webpack.js.org/loaders/svg-inline-loader/ <https://webpack.js.org/loaders/svg-inline-loader/>
Well, maybe a step in the wrong direction.

**Comment by jdtempleton** [comment]
> You are building your own copy of graphviz locally?

No, I am not building graphviz. I have just installed it via ```apt install graphviz graphviz-dev```
I have considered building from source, but haven't got to that point yet. One thing you mentioned got me wondering if I installed librsvg before graphviz. If I am installing graphviz using my package manager, would I need to have installed librsvg before graphviz or is that only necessary when building from source?

**Comment by magneticnorth** [comment]
You may need to ask the upstream package provider if it is not us.

**Comment by jdtempleton** [comment]
Do you have a link to some documentation on compiling graphviz from source? The page I have found has a broken link, which supposedly has a list of all the external package dependencies for building graphviz.

Here is the link for reference. https://graphviz.org/doc/build.html

**Comment by magneticnorth** [comment]
Sorry that’s broken. I didn’t realize.

All the raw content for the pre-Gitlab website is still on GitHub if that
helps in a pinch.

**Comment by ellson** [comment]
I'm wondering if this is a Debian packaging issue?   Loading of svg images
requires: librsvg2

On Fedora, you can see which libgvplugin  provides loadimage svg:cairo .
It should be in
libgvplugin_rsvg.so.6,  which on Fedora is packaged in
graphviz-plugins-x.    If the plugin won't load
when config6 is wriiting at installation time,  perhaps because of a
missing librsvg, then there will be no entry for it
in the config6 file.

For testing I moved the image to the same dir as the dot file.

I've attached the output.svg that I get on Fedora.

**Comment by jdtempleton** [comment]
This does appear to be a Debian packaging issue. Luckily, I was not tied to Debian since I am trying to build this in a Docker image. I tested using a Fedora Docker image and was successfully able to run the command with the svg:cairo plugin after installing graphviz using dnf.

Thanks for the help!

**Comment by parrt** [comment]
Actually, we just discovered that plain old `dot -Tsvg t.dot > t.svg`  works with some font issues even without librsvg installed. on the Mac I uninstalled and installed with just:

```
brew install graphviz --with-app --with-pango
```

 we are trying on linux now.

**Comment by jdtempleton** [comment]
Brew is a completely different packaging manager. Brew packages graphviz with librsvg. I have contacted the Debian package maintainer for graphviz and he has changed the way graphviz is packaged. It will include librsvg in it's installation now. It is currently available on Debian Buster.

Also, the -Tsvg option, only applies the path to the SVG in the output SVG. My use case is that I need the contents of the SVG to be appended into the output SVG, so the path doesn't matter. This is why the svg:cairo plugin was and is useful.

**Comment by parrt** [comment]
Re "Brew packages graphviz with librsvg." it only does if you use `--with-librsvg` I believe.

**Comment by jdtempleton** [comment]
@parrt Right, but there is no way to do this with apt packages on Debian unless you compile from source, which I and many others don't want to have to do. Which is why I contacted the Debian package maintainer and he has fixed the package in Debian Buster.

**Comment by parrt** [comment]
Yup. thanks! I'm trying linux now myself. my theory is that -Tsvg works if you import just .svg and without that librsvg. previously i was doing -Tpdf and importing .svg which didn't work on mac even until i installed that lib.

**Comment by jdtempleton** [comment]
@parrt When I used -Tsvg all it would do is copy the path to the SVG I was trying to embed into the new SVG, which doesn't work when trying to share the output SVG with others because they don't have the path to the original SVG. 

Take a look at my input and output files I mentioned above in my original post.

**Comment by parrt** [comment]
Yep, saw that. i wrote software that merges those to embed them. :)  So if i can get this to work then my dtreeviz will work on linux.

**Comment by parrt** [comment]
Ok, `dot -Tsvg t.dot > t.svg` just worked for me on ubuntu with apt get of graphviz. It has embedded image refs to *local* dir. my [embedding code](https://github.com/parrt/dtreeviz/blob/master/dtreeviz/utils.py) should solve the rest of the issues.

**Comment by jdtempleton** [comment]
@parrt  This issue has already been resolved via graphviz. This GitHub issue was not about your dtreeviz code. I don't understand why anyone would want to go the extra step of using your embedded inline svg conversion after running graphviz if graphviz will do the embedding for them.

**Comment by mbd-dbc-dk** [comment]
> Ok, `dot -Tsvg t.dot > t.svg` just worked for me on ubuntu with apt get of graphviz. It has embedded image refs to _local_ dir. my [embedding code](https://github.com/parrt/dtreeviz/blob/master/dtreeviz/utils.py) should solve the rest of the issues.

Thanks for putting this (the embedding code) up - believe it or not, some of us still run old (2018) versions of our os, and this script helped me getting some stuff done, so thanks. Only caveat: The modified node is appended, effectively blocking earlier nodes, if it has a fill, but that is easy to fix. Thanks again.

**Comment by CyberShadow** [comment]
> I don't understand why anyone would want to go the extra step of using your embedded inline svg conversion after running graphviz if graphviz will do the embedding for them.

For some reason GraphViz fails at embedding SVGs produced by https://latex.codecogs.com/ on my machine, it just inserts an empty 1x1 image. I had to work around this by using a PNG render of the SVG image, and then patching GraphViz' SVG output to replace the PNG with the SVG image, and inline it with @parrt's nice script.

**Comment by ApollonGT** [comment]
I had the same issue when using: https://github.com/mingrammer/diagrams
In Fedora it worked as expected but there was an issue on referencing SVG files in custom nodes, in Ubuntu.

The problem solved when I installed the packages: `librsvg2-dev` and `graphviz-dev`. I assume only `librsvg2-dev` is what I needed.
