### ISSUE TITLE
abort("Assertion failed: 0, at: trapezoid.c,88,newtrap")

### ISSUE THREAD

**Issue by Angeld55** [ellson/graphviz#1298]
This build just fine:
`digraph G { rankdir=LR; splines=ortho;
subgraph cluster_T1 {
style=invis
subgraph cluster_T1_0{
T1[shape=rect, height=3,width=0.23, fixedsize=true];
invis_node_T1_0[color = black, shape = point, width = 0.01, height = 0.01]; 
invis_node_T1_1[color = black, shape = point, width = 0.01, height = 0.01]; 
 
invis_node_T1_0-> T1:w[color =black];
invis_node_T1_1-> T1:w[color =black];

}
{ rank = same; p3;p4;}
T1 -> p3[color =black];
T1 -> p4[color =black];
//##### (without this) test -> T1:w[color = black]; 
 } 
subgraph cluster_T2 {
style=invis
subgraph cluster_T2_0{
T2[shape=rect, height=1,width=0.23, fixedsize=true];
invis_node_T2_0[color = black, shape = point, width = 0.01, height = 0.01]; 
invis_node_T2_0-> T2:w[color =black];

}
{ rank = same; p6;}
T2 -> p6[color =black];

 } 
subgraph cluster_T3 {
style=invis
subgraph cluster_T3_0{
T3[shape=rect, height=3,width=0.23, fixedsize=true];
invis_node_T3_0[color = black, shape = point, width = 0.01, height = 0.01]; 
invis_node_T3_0-> T3:w[color =black];

}
{ rank = same; p7;p8;p9;}
T3 -> p7[color =black];
T3 -> p8[color =black];
T3 -> p9[color =black];

 } 

p1 -> invis_node_T1_0[arrowhead=none, color = black];
p2 -> invis_node_T1_1[arrowhead=none, color = black];
p4 -> invis_node_T2_0[arrowhead=none, color = black];
p6 -> invis_node_T3_0[arrowhead=none, color = black];
}
`

But when I remove the `####` and leave the edge: `test -> T1:w[color = black];  `it stops to render with this error:
abort("Assertion failed: 0, at: trapezoid.c,88,newtrap")

**Comment by magneticnorth** [comment]
The project has been hosting on another repository for quite a few years.  Go to www.graphviz.org and click on the appropriate link at the top.  Probably this bug was fixed.
