### ISSUE TITLE
Missing stropts.h on Fedora 20

### ISSUE THREAD

**Issue by dilawar** [ellson/graphviz#23]
This bug https://bugzilla.redhat.com/show_bug.cgi?id=656245 causing build to fail on Fedora-20. Fedora-20 does not have 'stropts.h' file in glibc.

Any workaround it?

Details:
~~~~
make[3]: Entering directory `/home/dilawar/Bhandar/Applications/Visualization/graphviz_git/lib/sfio'
Making all in Sfio_f
make[4]: Entering directory `/home/dilawar/Bhandar/Applications/Visualization/graphviz_git/lib/sfio/Sfio_f'
  CC     _sfclrerr.lo
In file included from _sfclrerr.c:14:0:
../../../lib/sfio/sfhdr.h:208:21: fatal error: stropts.h: No such file or directory
 #include <stropts.h>
                     ^
~~~~

**Comment by embray** [comment]
FWIW @emdengrg's hint fixed this same issue for me.  Thanks!

**Comment by ellson** [comment]
Sounds like this issue is fixed, and anyway Fedora 20 is too old and no longer supported.
