### ISSUE TITLE
SVG viewBox problem with 2.38.0

### ISSUE THREAD

**Issue by gfredericks** [ellson/graphviz#27]
The following graph produces a bad SVG with `2.38.0`, while `2.36.0` does not seem to have the problem:

```
digraph G {
  graph [dpi = 300];
  node [fontname = "monospace"];
  n24 [label="24"];
  n83 [label="8⋅3"];
  n64 [label="6⋅4"];
  n122 [label="12⋅2"];
  n432 [label="4⋅3⋅2"];
  n622 [label="6⋅2⋅2"];
  n3222 [label="3⋅2⋅2⋅2"];
  n24 -> n83;
  n24 -> n64;
  n24 -> n122;
  n83 -> n432;
  n64 -> n432;
  n64 -> n622;
  n122 -> n622;
  n432 -> n3222;
  n622 -> n3222;
}
```

Here is the important part of the diff of the svg outputs (`2.38.0` is first, `2.36.0` is second):

```
7,8c7,8
< <svg width="902pt" height="1083pt"
<  viewBox="0.00 0.00 216.50 260.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
---
> <svg width="900pt" height="1083pt"
>  viewBox="0.00 0.00 900.00 1083.33" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

You can see in the first version the `viewBox` is no longer related to the `width` and `height` attributes. The result is that, for this particular graph, the image appears blank (presumably because there is nothing in that particular rectangle). If you manually adjust the output to be similar to the second version, the image appears fine.

**Comment by maxcountryman** [comment]
I ran into this issue as well using `graphviz-2.38.0`.

Is there a way to manually specify the `viewBox` dimensions?

**Comment by magneticnorth** [comment]
I’m not sure if this is a bug, but the ViewBox really is
related to the stated width and height.
This has something to do with setting dpi=300.
This setting is mainly intended for raster formats.
Path based output formats like SVG and PDF default to “dpi” of 72
but the example overrides this and sets 300 dpi. This probably
is not right for most SVG renderers.  

I think it’s similar to the effect you would get in the raster formats,
so I believe our code is correct.  How else would it process the dpi setting.

**Comment by maxcountryman** [comment]
I think this is happening on higher-resolution monitors, at least in my case I'm using a MBP with a Retina display--I'm not manually specifying the DPI.

How is the DPI setting populated by default?

**Comment by gfredericks** [comment]
now that you point that out I can't recall why I was setting the dpi to begin with (though it was 18 months ago now so there might've been a good reason)

**Comment by graphviz** [comment]
> On Feb 25, 2016, at 12:32 PM, Max Countryman <notifications@github.com> wrote:
> 
> I think this is happening on higher-resolution monitors, at least in my case I'm using a MBP with a Retina display--I'm not manually specifying the DPI.
> 
> How is the DPI setting populated by default?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ellson/graphviz/issues/27#issuecomment-188893203>.
> 

It's near the end of this file, https://github.com/ellson/graphviz/blob/master/plugin/core/gvrender_core_svg.c <https://github.com/ellson/graphviz/blob/master/plugin/core/gvrender_core_svg.c>
I can hardly believe someone wrote comments - probably John Ellon. The answers are…


gvrender_features_t render_features_svg = {
    GVRENDER_Y_GOES_DOWN | GVRENDER_DOES_TRANSFORM | GVRENDER_DOES_LABELS | GVRENDER_DOES_MAPS | GVRENDER_DOES_TARGETS | GVRENDER_DOES_TOOLTIPS,	/* flags */
    4.,				/* default pad - graph units */
    svg_knowncolors,		/* knowncolors */
    sizeof(svg_knowncolors) / sizeof(char *),	/* sizeof knowncolors */
    RGBA_BYTE,			/* color_type */
};

gvdevice_features_t device_features_svg = {
    GVDEVICE_DOES_TRUECOLOR|GVDEVICE_DOES_LAYERS,  /* flags */
    {0., 0.},			/* default margin - points */
    {0., 0.},			/* default page width, height - points */
    {72., 72.},			/* default dpi */
};

**Comment by graphviz** [comment]
> On Feb 25, 2016, at 12:35 PM, Gary Fredericks <notifications@github.com> wrote:
> 
> now that you point that out I can't recall why I was setting the dpi to begin with (though it was 18 months ago now so there might've been a good reason)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ellson/graphviz/issues/27#issuecomment-188894543>.
> 

I’m glad I’m not the only one!  Try code written 10 years ago.

**Comment by maxcountryman** [comment]
So unless I'm mistaken, this problem still occurs regardless of DPI. I can provide an example against `2.38.0` in a bit.

**Comment by maxcountryman** [comment]
Buried in a library I was using which wrapped GraphViz was an overload for the DPI that I missed before. Setting this back to 72 does in fact fix the issue for me.

**Comment by emdenrg** [comment]
My take on this is that, for non-bitmap output (svg, postscript, etc.), 
DPI should be ignored except for importing bitmap images, to translate 
the bitmap size into real-world size. For viewing non-bitmap output, it 
is the renderer's job to translate real-world units into the correct 
number of pixels for the device it is writing on.

**Comment by ellson** [comment]
Sounds like this issue is resolved ... closing
