### ISSUE TITLE
mkstemp not available on win32

### ISSUE THREAD

**Issue by tkelman** [ellson/graphviz#32]
I'm trying to work through a set of changes (mostly minor so far) to fix #19 and build Graphviz with MinGW-w64. In f8f7cbb67a1181a99b20618c798677832139ee61 a use of `mktemp` was replaced by `mkstemp`, apparently to fix a warning, but that function is not available in msvcrt. `mktemp` is deprecated but at least it's present - http://msdn.microsoft.com/en-us/library/ms235413.aspx. I believe this issue applies equally to MSVC but I haven't tested that.

There is a BSD-licensed `mkstemp` implementation for win32 available here https://github.com/storoj/libimobiledevice-win32/blob/master/libzip/mkstemp.c but I'm not sure how standalone it is.

**Comment by emden** [comment]
At present, this file is not being compiled in our Windows version and, as far as I can see, the 
functions in the file don't
seem to be used anywhere. John?

**Comment by tkelman** [comment]
With MinGW I am attempting to use `configure` and `make`, so if the MSVC build system is skipping large chunks of the library I could try to put code in the autotools files to make the same thing happen on MinGW.

**Comment by emden** [comment]
Until we find out how this code is being used, you could just put #if 0...#endif around it.
Now that I know it is there, I should add it to the Windows build, and supply an implementation of
mkstemp.

    Emden

**Comment by ellson** [comment]
The mkstemp was added recently due to dire warnings from gcc about the 
use of mktemp.

Feel free to override in the Windows code somehow.

John

**Comment by tkelman** [comment]
Something like
```
void *buffstderr(void)
{
#ifdef _WIN32
    char *p;
#else
    int t;
#endif
    struct buff_s *b;

    assert ((b = malloc(sizeof(struct buff_s))));
    assert ((b->template = strdup("/tmp/stderr_buffer_XXXXXX")));
#ifdef _WIN32
    assert ((p = mktemp(b->template)));
#else
    assert ((t = mkstemp(b->template)) > 0);
#endif
    fflush(stderr);
    fgetpos(stderr, &(b->pos));
    b->fd = dup(fileno(stderr));
    freopen(b->template, "w+", stderr);
    return (void *)b;
}
```
or did you have a more elegant solution in mind?

**Comment by ellson** [comment]
Tony,

Sounds good,  except that Coverity objects to side effects in assert(), so:

|	p =|||mktemp(b->template);
	assert (p);|  
     #else
	t = mkstemp(b->template);
	assert (t > 0);

Will you provide a patch?

John
|

**Comment by tkelman** [comment]
Sure, can do. I have a local branch where I've been adding various other little patches (mostly things like replacing `#ifdef WIN32` with `#ifdef _MSC_VER` for code that applies to MSVC but not MinGW), I could submit this little patch separately from the rest of those if you'd like. For review purposes would you rather look at a pull request with a large number of small patches, or a smaller number of larger patches?

**Comment by ellson** [comment]
Tony,

Either is fine.  Go ahead with your patches, thank you, but Emden points 
out that this stderr buffering code isn't actually used anywhere.  It 
looks like it is some half-finished project of mine ...
So, independent of your patch, I'm probably going to change 
lib/gvc/Makefile.am to not build this file for now.

John
