### ISSUE TITLE
Failed to compile under MinGW

### ISSUE THREAD

**Issue by hftmarkand** [ellson/graphviz#45]
Hello,

I have the following error when compiling with MinGW-w64:

graph.c:281:1: error: initializer element is not constant
 Agdisc_t AgDefaultDisc = { &AgMemDisc, &AgIdDisc, &AgIoDisc };
 ^
graph.c:281:1: error: (near initialization for 'AgDefaultDisc.mem')
graph.c:281:1: error: initializer element is not constant
graph.c:281:1: error: (near initialization for 'AgDefaultDisc.id')
graph.c:281:1: error: initializer element is not constant
graph.c:281:1: error: (near initialization for 'AgDefaultDisc.io')
make[3]: *** [graph.lo] Error 1

It's the version 2.38.0.

**Comment by emden** [comment]
See https://github.com/tkelman/graphviz/commit/6fc3f4c532c7722d718a422dbf306fcb59836e8d
The change has been added the main source tree.
