### ISSUE TITLE
Nightly build

### ISSUE THREAD

**Issue by kbrock** [ellson/graphviz#48]
I was looking into creating a nightly build using [travis](http://docs.travis-ci.com/user/languages/c/). It would run through the PRs and make sure they are valid before merging in the code.

1. Do we currently have an alternative nightly build with something like [jenkins](https://jenkins-ci.org/)?
2. We have [build](http://www.graphviz.org/doc/build.html) instrucitons but do we have test instructions?3. Would building just on a single operating system be good enough? (at least for starters)
4. Is this something that interests you? I have no problem doing the work, just don't want to do this work if you have an alternative / don't want.

Thanks,
Keenan

**Comment by graphviz** [comment]
We are definitely interested in this as most of the team has left AT&T so
the environment there has been stranded and AT&T doesn’t seem very
interested in the work any more.

The test setup is somewhat out of date and all it takes is for some font
rendering to change slightly and all the coordinates change. The rtest
can be updated but someone needs to manually look at the output and
confirm it is correct. Emden Gansner was doing this lately and knows
more of the specifics about this.

About packaging, we were using an obsolete package manager on the Macs
and we talked about migrating to whatever is customary in OSX these days.

**Comment by kbrock** [comment]
I've tried a few builds but build instructions don't quite match what works for me. Any pointers to requirements / build instructions for ubuntu?

[build command](https://github.com/kbrock/graphviz/blob/travis_builds/.travis.yml) produces: [build output](https://travis-ci.org/kbrock/graphviz/pull_requests)

Thanks

**Comment by magneticnorth** [comment]
Sorry. I don’t think we recommend “make check” or “make rtest” for non-developers
as there are likely to be problems. I doubt the regression tests are kept up to date --
lack of time on our part.

diffimg is a tool for comparing graphical output at the pixel level. It is in the
contrib directory of the graphviz build. You should get this with “make install”
of graphviz.

**Comment by kbrock** [comment]
thanks.

besides manual side by side checks, is there any way to ensure that a build was good?

**Comment by emden** [comment]
The regression tests can help find blatant errors, or places where 
Graphviz crashes, but subtle errors are
hard to find without looking at the figures side by side. Code changes 
can cause the drawing to shift a few
pixels, but still provide acceptable output. This would seem to be an 
interesting topic for research.

**Comment by kbrock** [comment]
ok, well make install has the same errors.
I'll need to setup an ubuntu box and see if I can get this stuff running there.

If you think of any other pre-requisites, please let me know.
