### ISSUE TITLE
Next release of Graphviz?

### ISSUE THREAD

**Issue by uxcq** [ellson/graphviz#73]
Have any plans been made? :(

**Comment by uxcq** [comment]
With your website down and other issues I guess not :-1:

**Comment by magneticnorth** [comment]
It’s up for me, but there’s apparently a routing problem inside AT&T Labs,
where we are still hosted.  

When John’s back we’ll probably pony up for commercial hosting, and move the site.
The bandwidth can be significant (2-3TB/month) though John had some ideas about
cutting back on irrelevant archives or moving them elsewhere.

**Comment by uxcq** [comment]
Why not host the page on Github https://pages.github.com/

**Comment by magneticnorth** [comment]
> On Mar 10, 2016, at 8:12 PM, John Bickmore <notifications@github.com> wrote:
> 
> Why not host the page on Github https://pages.github.com/ <https://pages.github.com/>
> —
> Reply to this email directly or view it on GitHub <https://github.com/ellson/graphviz/issues/73#issuecomment-195126764>.
> 
The current site has a lot of drupal content (forums, bug lists in mantis) and it has
a bunch of large files that are compressed source archives from the past.  I think the
main pages of the site are generated by Makefiles (like the docs that describe the
attributes).
